#!/bin/bash
# ============================================
# SAGE Development System — Installer
# ============================================
# 自己完結型。このスクリプトだけで SAGE を導入・更新できます。
#
# 新規導入: bash install.sh
# 更新:     bash install.sh --update
# バージョン確認: bash install.sh --version
#
# Generated by: scripts/generate-installer.sh
# ============================================
set -euo pipefail

SAGE_VERSION="0.2.0"

# === Embedded templates ===

read -r -d '' TMPL_SPEC <<'__EOF_TMPL_SPEC__' || true
# SPEC-XXXX: [タイトル]

## メタデータ

| フィールド | 内容 |
|-----------|------|
| SPEC-ID   | SPEC-XXXX |
| ステータス | Draft / Review / Approved / Implemented / Deprecated |
| 作成日    | YYYY-MM-DD |
| 更新日    | YYYY-MM-DD |
| 担当Agent | Spec Agent |
| 依存SPEC  | SPEC-YYYY（なければ "none"） |
| 権限レベル | system / platform / feature |

## 背景・目的

なぜこの変更を行うのか。どんな課題があるのか。

## 対象ユーザー

誰に影響するのか。

## スコープ（含む）

何を変えるか。変更対象を箇条書きで明示。

- 変更対象1
- 変更対象2

## スコープ外（明示的に除外）

何を変えないか。意図的に除外する範囲。
「なし」は不可 — 意識的に除外範囲を記述すること。

- 除外対象1
- 除外対象2

## 要件

### 機能要件
- [FR-01] ...
- [FR-02] ...

### 非機能要件
- [NFR-01] パフォーマンス: ...
- [NFR-02] 可用性: ...

### セキュリティ要件
- [SEC-01] ...
（「該当なし」の場合は理由を付記すること）

### 運用要件
- [OPS-01] ...

## 受け入れ条件（Acceptance Criteria）

コマンドまたはテストで検証可能な条件を記述。最低3件。

- [ ] AC-01: `make test` が全件パスする
- [ ] AC-02: `make lint` でエラーが0件
- [ ] AC-03: [具体的な業務条件]

## 異常系

最低1件定義すること。

- 想定エラー1: ...
- 想定エラー2: ...
- 境界ケース1: ...

## 契約

- API: OpenAPI spec path / なし
- DB: migration path / なし
- イベント: schema path / なし

## リスク

- リスク1: ... → 軽減策: ...

## 実装メモ（Implementation Agent向け）

実装時に参考にすべき既存コード・パターン・制約。

## 関連ID

- PLAN-ID: （計画フェーズで記入）
- TASK-ID: （分割フェーズで記入）

__EOF_TMPL_SPEC__

read -r -d '' TMPL_PLAN <<'__EOF_TMPL_PLAN__' || true
# PLAN-XXXX: [タイトル]

## メタデータ

| フィールド | 内容 |
|-----------|------|
| PLAN-ID   | PLAN-XXXX |
| SPEC-ID   | SPEC-XXXX |
| ステータス | Draft / Active / Completed |
| 作成日    | YYYY-MM-DD |
| 担当Agent | Planning Agent |

## 変更レイヤ

- [ ] controller
- [ ] usecase
- [ ] domain
- [ ] infrastructure
- [ ] frontend
- [ ] infra
- [ ] test

## 影響範囲

どの機能やモジュールに影響するか。

## 実装方針

どう実現するか。選択肢があれば比較。

## タスク分解

| TASK-ID | 責務 | 担当Agent | 見積 | 依存TASK | 並列可否 |
|---------|------|----------|------|---------|---------|
| TASK-0001 | ... | Implementation | 1h | - | Yes |
| TASK-0002 | ... | Test | 30m | TASK-0001 | No |

## リスク

- リスク1: ... → 軽減策: ...

## 必要な検証

- [ ] unit test
- [ ] integration test
- [ ] security scan
- [ ] e2e test
- [ ] architecture boundary check

__EOF_TMPL_PLAN__

read -r -d '' TMPL_TASK <<'__EOF_TMPL_TASK__' || true
# TASK-XXXX: [タイトル]

## メタデータ

| フィールド | 内容 |
|-----------|------|
| TASK-ID   | TASK-XXXX |
| SPEC-ID   | SPEC-XXXX（必須） |
| PLAN-ID   | PLAN-XXXX（必須） |
| ステータス | Pending / In Progress / Review / Done |
| 担当Agent | Implementation / Test / Security / Review |
| 並列可否  | Yes / No |
| 依存TASK  | TASK-YYYY / none |
| 見積     | [時間] |

## 責務

このタスクが担う単一責務。1文で記述。

## 入力

必要な仕様や前提条件。

## 出力

期待される成果物（ファイルパス、テスト結果等）。

## File Scope（変更許可範囲）

- 作成: [パス]
- 変更: [パス]
- 削除: [パス]

## 禁止事項

触ってはいけない範囲・やってはいけないこと。

## 完了条件

コマンドベースで検証可能な条件を1件以上。

- [ ] `make test` が全件パスする
- [ ] [具体的な完了判定]

## Done Definition（ラウンド単位）

参照: `tasks/done-def-SPEC-XXXX-round-N.md`（実装開始前に作成）

Done Definition は SPEC 単位・ラウンド単位で作成する。
テンプレート: `templates/done-definition-template.md`

## 実行ログ

| フィールド | 内容 |
|-----------|------|
| RUN-ID    | RUN-XXXX（実行時に自動採番） |
| 開始     | YYYY-MM-DD HH:MM |
| 完了     | YYYY-MM-DD HH:MM |
| 結果     | Pass / Fail |
| Gate結果  | structural: ○ / functional: ○ / security: ○ |

__EOF_TMPL_TASK__

read -r -d '' TMPL_CHARTER <<'__EOF_TMPL_CHARTER__' || true
# SAGE憲章 v0.1

## 1. 存在目的

SAGEは、AIを使って開発速度を上げるための仕組みではない。

**複数のAIが同時に開発しても、品質・安全性・一貫性が崩れない開発体系を実現するための仕組み**である。

## 2. 最上位原則

**仕様が最上位の真実である。**

コード、会話、口頭指示、個人の解釈は、仕様に従属する。

## 3. AIの位置づけ

AIは万能な実装者ではない。

AIは、**仕様・役割・権限・制約・検証の中で働く実行者**である。

## 4. 品質の考え方

品質は、優秀なモデルから生まれない。

**品質は、壊れにくい構造と強い検証から生まれる。**

## 5. 並列開発の考え方

並列化とは、AIを増やすことではない。

**責務を分け、粒度を整え、統合可能な単位に切ること**である。

## 6. 人間の責務

人間は、実装の主担当ではない。

人間は、**目的を定義し、仕様を承認し、優先順位を決め、例外を判断し、最終責任を持つ監督者**である。

## 7. 守るべき設計姿勢

- 仕様なしに実装しない
- 1回の大生成で大機能を作らない
- AIに無制限の権限を与えない
- ルールを文章だけで終わらせない
- CI未通過の変更を統合しない
- 実行履歴を残さない開発をしない

## 8. SAGEの約束

SAGEは次を保証するために存在する。

- 何を作るかが追える
- 誰が何を変えたかが追える
- どの仕様から変更が生まれたかが追える
- なぜ落ちたかが分かる
- どう直すかが再現できる

## 9. 設計根拠 — 5つのソースから得た思想

SAGEは5つのソースの**思想・設計哲学**を統合して生まれた。ソースコードの統合ではない。各ソースから何を学び、SAGEのどの層に反映したかを以下に明記する。

### 9.1 go-boilerplate —「構造で守る」
- AIが触っても壊れにくいコードベースを**先に設計する**思想
- OpenAPI契約→型生成→レイヤ分離（Onion Architecture）→sqlc型安全SQLにより、依存方向・境界・型で**構造的に逸脱を不可能にする**
- SAGEの **Codebase Layer** の根拠
- 参照: https://github.com/Tomy-ch/go-boilerplate

### 9.2 ai-development-patterns —「パターンで規律する」
- AI開発の成功/失敗を27の再現可能なパターンに体系化した思想
- Foundation（準備）→ Development（実行）→ Operations（運用）の3段階成熟モデル
- アンチパターン（implementation-first, big bang, unrestricted access）を名付けて禁止し、**失敗をパターンとして検出可能にしCIで止める**
- SAGEの **Governance Layer** の根拠
- 参照: https://github.com/PaulDuvall/ai-development-patterns

### 9.3 auto-dev —「役割で分業する」
- SDLC全体（要件→開発→レビュー→テスト→データ→デプロイ→運用）を7エージェントで分担する思想
- 1つのAIに全部やらせるのはワンマン経営と同じ。**責務を分けてこそスケールする**
- SAGEの **Runtime Layer** の根拠
- 参照: https://github.com/phodal/auto-dev

### 9.4 awesome-AI-driven-development —「ツールは役割で選ぶ」
- 522+ツールを機能カテゴリ（IDE/CLI/オーケストレーション/テスト/セキュリティ/レビュー/知識管理）で整理した全体図
- 特定製品に依存せず、**役割ごとにスロットを定義**して差し替え可能にする思想
- SAGEの **Tooling Layer** の根拠
- 参照: https://github.com/AIDrivenDevelopment/awesome-AI-driven-development

### 9.5 Spec-Driven Development —「仕様が真実」
- Requirements → Specification → AI Generation → Validation の流れで、仕様を source of truth とする思想
- AIは指示が明確なら優秀に動く。問題はAIの能力ではなく**指示の品質**。だから仕様を最上位に置く
- 人間の役割は実装からアーキテクチャ・要件・検証へシフトする
- SAGEの **Philosophy Layer** の根拠
- 参照: https://www.softwareseni.com/spec-driven-development-in-2025-the-complete-guide-to-using-ai-to-write-production-code/

### 9.6 統合

SAGEはこの5つを1文に統合したものである。

> **仕様で始め（Spec-Driven）、パターンで規律し（ai-dev-patterns）、役割で分け（auto-dev）、構造で守り（go-boilerplate）、ツールを役割で選ぶ（awesome-AI-driven-dev）**

---

## 10. 最終宣言

**AI駆動開発とは、AIに上手く書かせる技術ではなく、AIが勝手に逸脱しにくい構造を先に作る技術である。**

__EOF_TMPL_CHARTER__

read -r -d '' TMPL_GOVERNANCE <<'__EOF_TMPL_GOVERNANCE__' || true
# SAGE Governance v0.1

## 1. 基本原則

### 原則1: 仕様がコードより上位
すべての変更は、仕様変更・仕様追加・仕様削除のいずれかとして扱う。コード単体の変更は存在しない。

### 原則2: AIは仕様を実行する
AIは仕様を解釈・実装・検査するが、仕様なき意思決定主体にはならない。

### 原則3: タスクは小さく独立可能
大きな要求をそのまま1エージェントに投げない。並列実行の前提は分割設計である。

### 原則4: AIは役割で分業する
要件、計画、実装、レビュー、テスト、セキュリティ、運用を分離する。

### 原則5: ルールは実行可能でなければならない
文章だけのルールは補助でしかない。型、lint、schema、policy、CIに落ちて初めて有効である。

### 原則6: コードベースは壊れにくく設計する
契約、依存方向、境界、ディレクトリ責務、生成コード分離を固定する。

### 原則7: 品質は生成ではなく検証で守る
AI出力を信用しない。通すべき検証を増やす。

### 原則8: 人間は監督者である
人間の仕事は、仕様策定、優先順位付け、例外判断、承認、改善である。

### 原則9: 開発は観測可能でなければならない
どの仕様から、どのタスクが生まれ、どのAIが何を変更したか追跡できること。

### 原則10: ツールはレイヤ別に選ぶ
エディタ、CLI、オーケストレーション、テスト、セキュリティ、レビュー、知識管理を役割別に構成する。

---

## 2. 標準ライフサイクル（7段階）

### Phase 1: Specify
目的、対象、ユースケース、成功条件、非機能要件、リスク、API契約、データ契約、異常系、監視条件を書く。曖昧な要求を残してはいけない。

### Phase 2: Plan
仕様をアーキテクチャに落とす。どのレイヤを触るのか、影響範囲はどこか、どのエージェントが担当するのか、どんな検証が必要かを決める。

### Phase 3: Slice
仕事を小さい単位に分ける。1タスク1責務を原則とし、依存関係、並列可否、統合順序を明示する。

### Phase 4: Execute
役割分担されたエージェントが実装・レビュー・テスト作成を進める。許可された責務範囲外の変更は禁止する。

### Phase 5: Verify
機械検証を行う。lint、type check、schema validation、unit / integration / e2e test、SAST、secret scan、architecture rule check を通す。

### Phase 6: Merge
検証済み変更だけを統合する。並列変更は順番付きで統合し、衝突解決ルールを持つ。

### Phase 7: Observe
本番観測を行い、仕様との差分やAIの失敗パターンを次回のルール・仕様テンプレへ反映する。

#### 3層計測設計

| 層 | 問い | 計測対象 |
|----|------|---------|
| ログ | What happened? | 各操作の成功/失敗・エラー内容・処理時間 |
| メトリクス | How often / How much? | エラー率・レイテンシ・スループット・カバレッジ推移 |
| アラート | Something wrong? | 閾値超過の自動検知・チーム通知 |

#### フィードバックループ

本番シグナルが次の開発サイクルの起点になる:

```
本番イベント → ログ記録 → 閾値超過 → アラート通知 → SPEC追記 → 修正Wave実行
```

#### Observe フェーズの必須アクション
1. デプロイ後の監視が設定されていることを確認
2. 発生した障害・異常を `sage/failures.md` に記録
3. 繰り返すパターン（3回以上）は `sage/anti-patterns.md` に昇格
4. 計測結果を `.sage/metrics/` に蓄積（Phase D以降）

---

## 3. エージェント責務

### 3.1 Spec Agent
仕様の作成と明確化を担当。曖昧さ、不足、衝突、未定義の異常系を検出する。

### 3.2 Planning Agent
仕様を実装計画に変換。影響レイヤ、必要成果物、依存関係、品質ゲートを整理する。

### 3.3 Task Slicing Agent
計画を小さい作業単位へ落とす。並列可能性を評価し、タスクグラフを作る。

### 3.4 Implementation Agent
許可された範囲で実装を行う。仕様にない振る舞いの追加は禁止する。

### 3.5 Review Agent
責務逸脱、アーキテクチャ違反、仕様不整合、不要複雑化を検出する。

### 3.6 Test Agent
受け入れ条件からテストケースを作成する。正常系だけでなく異常系、境界値、回帰条件も作る。

### 3.7 Security & Policy Agent
秘密情報、脆弱性、権限違反、危険な依存、ポリシー違反を検査する。

### 3.8 Operations Agent
デプロイ準備、監視設定、リリース後観測、インシデント学習を担当する。

### エージェント最小構成（Claude Code単独時）

| 構成 | 役割 |
|------|------|
| Session A | Spec / Planning / TaskSlicing |
| Session B | Implementation |
| Session C | Review / Test |
| CI | Security & Policy |
| Human | Operations（承認・判断） |

---

## 4. エージェント運用ルール

### 4.1 分離原則
同じエージェントが以下を同時に持つのを避ける:
- 実装と最終承認
- 実装とセキュリティ承認
- 実装と本番反映判断

### 4.2 エージェント指示の4必須要素

エージェントへの指示には、以下の4要素を必ず含める。
曖昧な指示はエージェントが合理的な仮定を積み重ね、意図とズレた実装を返す。

| 要素 | 内容 | 悪い例 | 良い例 |
|------|------|--------|--------|
| ① 目標 | 動詞で始め、成果物を明示 | 「認証を実装して」 | 「POST /api/auth/login を実装し、JWTを返す関数を作成」 |
| ② スコープ | 触れるファイルを列挙。「これ以外は変更禁止」と明言 | 「認証周りを修正」 | 「src/auth/login.ts, src/auth/types.ts のみ変更可」 |
| ③ 文脈 | 前フェーズの成果物を直接貼る（スキーマ・型定義等） | 「DBと整合を取って」 | 「以下のスキーマを参照: (SQLを貼付)」 |
| ④ 完了条件 | テストのPass/Failで定義。「動けばいい」は禁句 | 「正しく動くこと」 | 「型エラー0件、make test全件Pass、未認証で401を返す」 |

**暗黙の依存のサイン**: 「〜と整合を取りながら」が指示に出てきたら、ファイル名とインタフェースを明示する。

### 4.3 エージェントへの禁止事項
AIに以下を許可しない:
- スコープ外変更
- サイレント仕様変更
- テスト省略
- 例外系未定義のまま進行
- 既存境界をまたぐ無断修正
- 実行ログなしの変更

---

## 5. マルチエージェント競合解決

複数エージェントが同時に作業する場合の優先チェーン:

**Security > Review > Implementation**

- TASK-ID別にブランチを分ける
- マージ競合はReview Agentが判断
- セキュリティ指摘はすべてのマージをブロック

---

## 6. 禁止事項

- 仕様なし実装
- 1回の大きな生成で主要機能を完成させようとすること（Big Bang Prompt）
- 権限境界なしでAIに広範な変更権限を与えること
- 実行ログを残さないこと
- CI未通過の変更を統合すること（Vibe Merge）
- 人の勘だけで本番品質判定を行うこと
- 役割の異なるエージェント責務を曖昧にすること（AI Monolith）
- 生成コードを手で直接修正し続けること

---

## 7. 人間の責務

SAGEにおける人間の責務:

- 目的定義
- 仕様の承認
- 優先順位付け
- リスク判断
- 例外承認
- 最終統合判断
- 失敗学習の反映

人間は**実装者中心**から**開発システムの監督者**へ役割が移る。

---

## 8. バイブコーディングとSDDの使い分け

SAGEは「仕様なしに実装しない」を原則とするが、探索フェーズでは例外を認める。

### バイブコーディング（探索用）が許される場面
- プロトタイピング・PoC
- 新技術のフィージビリティ確認
- UIの見た目確認・デザイン探索
- 小規模ユーティリティの試作

### SDD（本番実装用）が必須の場面
- 本番システムへのデプロイ
- チーム開発・並列エージェント開発
- 複雑なアーキテクチャ変更
- セキュリティ・コンプライアンス要件

### 移行ルール
バイブコーディングで作ったものを本番に持ち込む場合は、
**必ず事後でもSPECを書き、品質ゲートを通す**こと。
「探索で書いたコードをそのまま本番に入れる」はアンチパターンとして扱う。

### ブランチ規約
- `vibe/*` ブランチから `main` への直接マージ禁止
- `vibe/*` → `staging` → （SPEC作成後） → `main` のフローを強制
- CIで `vibe/*` ブランチからの直接マージを検出・警告する

__EOF_TMPL_GOVERNANCE__

read -r -d '' TMPL_FAILURES <<'__EOF_TMPL_FAILURES__' || true
# SAGE Failures Log

アンチパターンの実例記録。繰り返し発生するパターンは `anti-patterns.md` に昇格する。

## 記録ルール

- 失敗が発生したら即座に記録する
- 同じ失敗が3回発生したら `anti-patterns.md` に昇格する
- 昇格後もこのログは削除しない（履歴として残す）

---

## エントリフォーマット

### FAIL-XXXX
- **発生日**: YYYY-MM-DD
- **TASK-ID**: TASK-XXXX
- **該当アンチパターン**: (あれば) Vibe Merge / Big Bang Prompt / Silent Scope Expansion / AI Monolith / Invisible Development / Human-Only Guard
- **症状**: 何が起きたか
- **根本原因**: なぜ起きたか
- **修正**: どう直したか
- **防止策**: 今後どう防ぐか（CI追加 / ルール追加 / テンプレ修正等）
- **昇格済み**: Yes / No（anti-patterns.mdに追加済みか）

---

## 記録

### FAIL-0001
- **発生日**: 2026-04
- **TASK-ID**: SAGE-QUALITY-001
- **該当アンチパターン**: なし（新規パターン）
- **症状**: PRレビューでtrailing whitespace / 既存パターンと異なる記法 / 目的不明なコードが繰り返し指摘される
- **根本原因**: AIが「動くコード」優先で既存ファイルの書式・パターンを確認せず、可読性・保守性の観点が欠落していた
- **修正**: src-rules に Code readability セクション追加、sage-review に Code Quality 観点追加、sage-validate.sh にノイズ差分検出追加
- **防止策**: セルフレビュー（src-rules）+ レビュー（sage-review）+ CI（sage-validate.sh Check 6）の3層で担保
- **昇格済み**: No

__EOF_TMPL_FAILURES__

read -r -d '' TMPL_ANTIPATTERNS <<'__EOF_TMPL_ANTIPATTERNS__' || true
# SAGE アンチパターン

## 概要

SAGEでは以下を明確に失敗パターンとして定義する。各パターンに**検出シグナル**と**CI検出方法**を付与し、Human-Only Guard（ルールが文章だけで止まらない）を防ぐ。

---

## AP-01: Vibe Merge

**定義**: なんとなく良さそうだから統合する。

**検出シグナル**:
- PRがどの品質ゲートも通過せずにマージされた
- レビューコメントが0件でマージされた

**CI検出方法**:
- GitHub branch protection で必須ステータスチェックを設定
- `sage-structural-gate` + `sage-security-gate` を required に設定

**防止策**: Branch protection の required status checks を有効化

---

## AP-02: Big Bang Prompt

**定義**: 巨大な要求を1回の生成で済ませようとする。

**検出シグナル**:
- 単一コミットで20ファイル以上を変更
- TASK-IDなしで大量変更
- 1つのPRに複数のSPEC-IDが混在

**CI検出方法**:
```bash
# sage-trace-check.sh で検出可能
FILES_CHANGED=$(git diff --name-only HEAD~1 | wc -l)
if [ "$FILES_CHANGED" -gt 20 ]; then
  echo "WARNING: Big Bang Prompt detected ($FILES_CHANGED files in one commit)"
fi
```

**防止策**: Slice フェーズで1タスク1責務に分割

---

## AP-03: Silent Scope Expansion

**定義**: 仕様にない変更をついでに入れる。

**検出シグナル**:
- TASK-IDの File Scope 外のファイルが変更されている
- PRの変更ファイルがTASKの「出力」セクションに列挙されていない

**CI検出方法**:
- Architecture Gate (Gate 4) でファイルスコープをチェック
- PRテンプレートのチェックリストで手動確認

**防止策**: TASK テンプレートの File Scope を厳密に記入

---

## AP-04: AI Monolith

**定義**: 1つのAIに仕様、実装、レビュー、テスト、判断を全部持たせる。

**検出シグナル**:
- 同一セッションで SPEC 作成 → 実装 → レビュー → マージ承認が行われた
- AGENT-ID がすべて同一

**CI検出方法**:
- 実行ログ（.sage/runs/）で AGENT-ID の多様性をチェック
- 実装エージェントとレビューエージェントの分離を検証

**防止策**: CLAUDE.md の Agent Constraints に分離ルールを記載

---

## AP-05: Invisible Development

**定義**: 誰が何をしたか分からない。

**検出シグナル**:
- コミットメッセージに TASK-ID が含まれていない
- PR本文に SPEC-ID が含まれていない
- `.sage/runs/` にログが存在しない

**CI検出方法**:
```bash
# sage-trace-check.sh で検出
git log --oneline -n 1 | grep -qE 'TASK-[0-9]{4}' || echo "WARNING: Invisible Development"
```

**防止策**: Traceability Requirements を CI で強制

---

## AP-06: Human-Only Guard

**定義**: ルールが文章しかなく、違反しても止まらない。

**検出シグナル**:
- `sage/` のルールに対応するCIチェックが存在しない
- `CLAUDE.md` の Forbidden Shortcuts が CI で検証されていない

**CI検出方法**:
- `sage-validate.sh` でルール文書と CI workflow の対応を確認

**防止策**: すべてのルールは CI または pre-commit hook で強制

---

## 昇格ルール

`sage/failures.md` に記録された失敗が**3回以上繰り返された場合**、このファイルに新しいアンチパターンとして追加する。

昇格時の必須項目:
1. AP-XX 番号の採番
2. 定義（1文）
3. 検出シグナル（観測可能な事象）
4. CI検出方法（自動化可能なチェック）
5. 防止策（具体的な対応）

__EOF_TMPL_ANTIPATTERNS__

read -r -d '' TMPL_QUALITY_GATES <<'__EOF_TMPL_QUALITY_GATES__' || true
# SAGE 品質ゲート定義

## 概要

SAGEでは5段階の品質ゲートを定義する。すべてのゲートはCIで自動実行され、マージ前に通過が必須。

---

## Gate 1: Structural（構造）

**トリガー**: すべてのPR（ドキュメント変更を除く）

| チェック | ツール例 | 必須 |
|---------|---------|------|
| Lint | golangci-lint / ESLint / ruff | Yes |
| Format | gofmt / prettier / black | Yes |
| Type check | go vet / tsc / mypy | Yes |
| Schema validation | oapi-codegen check / sqlc check | 条件付き |
| SAGE structure | sage-validate.sh | Yes |
| Noise diff check | git diff --check | Yes |

**閾値**: エラー0件で通過。Warning は許容するがログに記録。
ノイズ差分（trailing whitespace、行末改行変更など変更意図のない差分）: 0件。

**注**: `git diff --check` はwhitespace系の差分のみ検出。変更意図のないリフォーマット、既存パターンとの不整合、投機的コードの混入はセルフレビュー（src-rules）およびレビュー（sage-review）で担保する。

---

## Gate 2: Functional（機能）

**トリガー**: `src/**` または `tests/**` の変更時

| チェック | ツール例 | 必須 |
|---------|---------|------|
| Unit test | go test / jest / pytest | Yes |
| Integration test | テストスイート | 条件付き |
| Coverage | octocov / jest --coverage | Yes |

**閾値**:
- カバレッジ: **80%以上**（`.sage/config.yaml` で調整可）
- テスト: 全件パス
- カバレッジが既存より低下した場合は失敗

---

## Gate 3: Security（セキュリティ）

**トリガー**: すべてのPR + 週次スケジュール

| チェック | ツール例 | 必須 |
|---------|---------|------|
| Secret scan | Gitleaks | Yes |
| Dependency vuln scan | Trivy | Yes |
| SAST | CodeQL / Semgrep | 条件付き |

**閾値**:
- Secret 検出: 0件で通過（1件でも失敗）
- 脆弱性: CRITICAL/HIGH は0件必須。MEDIUM は記録のみ。

---

## Gate 4: Architecture（アーキテクチャ）

**トリガー**: `src/**` の変更時

| チェック | ツール例 | 必須 |
|---------|---------|------|
| Layer boundary | カスタムスクリプト / archunit | Yes |
| Forbidden dependency | import解析 | Yes |
| Traceability | sage-trace-check.sh | Yes |

**閾値**:
- レイヤ境界違反: 0件
- TASK-ID未記載コミット: 0件（初期コミット・マージコミットを除く）

---

## Gate 5: Release（リリース）

**トリガー**: main/production への PR

| チェック | 内容 | 必須 |
|---------|------|------|
| Migration safety | マイグレーションの可逆性確認 | Yes |
| Rollback plan | ロールバック手順の存在 | Yes |
| Monitoring readiness | 監視設定の確認 | Yes |
| Gate 1-4 すべて通過 | 前提条件 | Yes |

**閾値**: すべてのチェックが通過で合格。

---

## マージ条件（すべて満たすこと）

- [ ] 仕様にひもづいている（SPEC-ID あり）
- [ ] タスク責務が単一（TASK-ID あり）
- [ ] 検証が通っている（Gate 1-3 必須、Gate 4-5 条件付き）
- [ ] レビュー指摘が解消済み
- [ ] 実行ログが残っている（RUN-ID）

__EOF_TMPL_QUALITY_GATES__

read -r -d '' TMPL_ADOPTION <<'__EOF_TMPL_ADOPTION__' || true
# SAGE 導入フェーズ

## 概要

SAGEは一気に全部導入しない。4段階で段階的に導入する。

---

## Phase A: Foundation

**目的**: 最小限の仕組みを入れる。

### チェックリスト

- [ ] `CLAUDE.md` を作成し、10必須セクションを記入
- [ ] `sage/charter.md` を確認（変更不要なら承認）
- [ ] `sage/governance.md` を確認
- [ ] `specs/_template.md` が存在する
- [ ] `plans/_template.md` が存在する
- [ ] `tasks/_template.md` が存在する
- [ ] `.sage/config.yaml` が存在する
- [ ] `.gitignore` に `.sage/runs/` と `.sage/metrics/` が追加されている
- [ ] 最初の SPEC（SPEC-0001）を作成した
- [ ] `make validate` が ALL PASSED

### 必要ファイル
```
CLAUDE.md
sage/charter.md
sage/governance.md
sage/failures.md
.sage/config.yaml
specs/_template.md
plans/_template.md
tasks/_template.md
.gitignore
```

### 次のフェーズへの移行条件
- 上記チェックリストがすべて完了
- 最低1つのSPEC→PLAN→TASKサイクルを回した

---

## Phase B: Guardrails

**目的**: 品質ゲートを設定し、ルールをCIで強制する。

### チェックリスト

- [ ] `.github/workflows/sage-structural-gate.yml` がプロジェクトに合わせて設定済み
- [ ] `.github/workflows/sage-functional-gate.yml` がプロジェクトに合わせて設定済み
- [ ] `.github/workflows/sage-security-gate.yml` が動作確認済み
- [ ] `.github/pull_request_template.md` が配置されている
- [ ] `sage/quality-gates.md` の閾値が確認済み
- [ ] `sage/anti-patterns.md` がチーム内で共有済み
- [ ] Branch protection が設定されている（required status checks）
- [ ] 生成コードと手書きコードが分離されている

### 必要ファイル（Phase Aに追加）
```
.github/workflows/sage-structural-gate.yml
.github/workflows/sage-functional-gate.yml
.github/workflows/sage-security-gate.yml
.github/pull_request_template.md
.github/settings/labels.json
sage/quality-gates.md
sage/anti-patterns.md
```

### 次のフェーズへの移行条件
- 品質ゲート3種（Structural, Functional, Security）がPRで自動実行される
- ゲート未通過のPRがマージされない設定が有効

---

## Phase C: Multi-Agent

**目的**: エージェント分業を開始し、並列開発の基盤を作る。

### チェックリスト

- [ ] `.claude/prompts/` に最低4種のエージェントプロンプトが配置
- [ ] 実装AIとレビューAIが分離されている
- [ ] テストAIが導入されている（または人間がテストを担当）
- [ ] `scripts/sage-validate.sh` が正常動作する
- [ ] `scripts/sage-trace-check.sh` が正常動作する
- [ ] `.github/workflows/sage-architecture-gate.yml` が設定済み
- [ ] `.github/workflows/sage-claude-review.yml` が設定済み
- [ ] TASK-ID別にブランチを分けるワークフローが確立
- [ ] 実行ログを `.sage/runs/` に記録する習慣がある

### 必要ファイル（Phase Bに追加）
```
.claude/prompts/spec-agent.md
.claude/prompts/planning-agent.md
.claude/prompts/implementation-agent.md
.claude/prompts/review-agent.md
.claude/prompts/test-agent.md
.claude/prompts/security-agent.md
.claude/prompts/operations-agent.md
.claude/settings.json
.github/workflows/sage-architecture-gate.yml
.github/workflows/sage-claude-review.yml
scripts/sage-validate.sh
scripts/sage-trace-check.sh
scripts/sage-id-gen.sh
scripts/sage-adopt.sh
```

### 次のフェーズへの移行条件
- 最低3回のマルチエージェント開発サイクルを完了
- エージェント間の責務分離が機能している

---

## Phase D: Learning System

**目的**: 学習サイクルを回し、SAGEを進化させる。

### チェックリスト

- [ ] `sage/failures.md` に失敗が記録されている
- [ ] 3回以上繰り返す失敗が `sage/anti-patterns.md` に昇格されている
- [ ] メトリクス（cycle_time, gate_pass_rate, rework_rate）を計測している
- [ ] 仕様テンプレートが実績に基づいて改善されている
- [ ] エージェントプロンプトが実績に基づいて調整されている
- [ ] `.github/workflows/sage-release-gate.yml` が設定済み
- [ ] Observe フェーズが各リリースで実行されている

### 必要ファイル（Phase Cに追加）
```
.github/workflows/sage-release-gate.yml
sage/adoption-phases.md
sage/traceability.md
docs/architecture.md
docs/rules.md
docs/development-flow.md
specs/SPEC-0001-example.md
```

### 成熟の指標
- Gate初回通過率 >= 80%
- リワーク率 <= 20%
- サイクルタイム（p50）<= 24h
- 新規アンチパターンの発生頻度が減少傾向

__EOF_TMPL_ADOPTION__

read -r -d '' TMPL_TRACEABILITY <<'__EOF_TMPL_TRACEABILITY__' || true
# SAGE トレーサビリティ

## ID体系

| ID種別 | フォーマット | 例 | 生成方法 |
|--------|-----------|-----|---------|
| SPEC-ID | SPEC-XXXX | SPEC-0001 | `make id-gen TYPE=spec` |
| PLAN-ID | PLAN-XXXX | PLAN-0001 | `make id-gen TYPE=plan` |
| TASK-ID | TASK-XXXX | TASK-0001 | `make id-gen TYPE=task` |
| RUN-ID | RUN-XXXX | RUN-0001 | `make id-gen TYPE=run` |
| FAIL-ID | FAIL-XXXX | FAIL-0001 | `make id-gen TYPE=fail` |
| MERGE-ID | PR番号 | #42 | GitHub自動 |

## 追跡チェーン

```
SPEC-ID → PLAN-ID → TASK-ID → AGENT-ID → RUN-ID → MERGE-ID
```

すべての変更はこのチェーンで追跡可能でなければならない。

## 記録場所

| ID | 記録場所 |
|----|---------|
| SPEC-ID | `specs/SPEC-XXXX-*.md` + PR本文 |
| PLAN-ID | `plans/PLAN-XXXX-*.md` + PR本文 |
| TASK-ID | `tasks/TASK-XXXX-*.md` + コミットメッセージ + PR本文 |
| RUN-ID | `.sage/runs/RUN-XXXX.yaml` |
| FAIL-ID | `sage/failures.md` |
| MERGE-ID | GitHub PR |

## 必須ルール

1. **すべてのPR** に SPEC-ID, PLAN-ID, TASK-ID を含む
2. **すべてのコミット** に TASK-ID を含む（形式: `feat: description [TASK-0001]`）
3. **すべてのエージェント実行** に RUN-ID を記録
4. **すべての失敗** に FAIL-ID を記録

## コミットメッセージ形式

```
<type>: <description> [TASK-XXXX]

Types: feat, fix, refactor, test, docs, chore, ci
```

例:
```
feat: add user authentication endpoint [TASK-0003]
fix: resolve null pointer in payment flow [TASK-0015]
test: add boundary tests for date validation [TASK-0016]
```

## 検証方法

```bash
# 直近コミットのTASK-ID存在チェック
make trace-check

# 自動検証（CI: sage-architecture-gate.yml）
# - PR本文のSPEC-ID存在チェック
# - コミットのTASK-ID存在チェック
# - Big Bang Prompt検出（20ファイル超の単一コミット）
```

__EOF_TMPL_TRACEABILITY__

read -r -d '' TMPL_CONFIG <<'__EOF_TMPL_CONFIG__' || true
# SAGE Runtime Configuration v0.1
# This file defines quality gate thresholds, metrics schemas, and runtime settings.

# --- Quality Gates ---
quality_gates:
  structural:
    lint: required
    format: required
    type_check: required
  functional:
    unit_test_coverage: 0.80  # 80% minimum
    integration_test: required
  security:
    secret_scan: required
    dependency_vuln: required
    sast: required
  architecture:
    layer_boundary: required
    traceability: required
  release:
    migration_safety: required
    rollback_plan: required
    monitoring_ready: required

# --- Metrics ---
metrics:
  cycle_time:
    measure: "SPEC作成からPRマージまでの時間（時間単位）"
    source: "GitHub API: issue created_at → PR merged_at"
    target_p50: "24h"
  gate_pass_rate:
    measure: "CIゲート初回通過率"
    source: "GitHub Actions: jobs結果"
    target: ">= 0.8"
  rework_rate:
    measure: "同一TASK-IDに対する再コミット率"
    source: "git log --grep=TASK-ID"
    target: "<= 0.2"

# --- Run Log Schema ---
run_log_schema:
  format: "yaml"
  location: ".sage/runs/{RUN-ID}.yaml"
  fields:
    run_id: "RUN-XXXX"
    task_id: "TASK-XXXX"
    agent_id: "spec | planning | implementation | review | test | security | operations"
    started_at: "ISO 8601"
    completed_at: "ISO 8601"
    status: "pass | fail | skipped"
    files_changed: []
    gate_results:
      structural: "pass | fail"
      functional: "pass | fail | skipped"
      security: "pass | fail"
    error_log: ""

# --- ID Schema ---
id_schema:
  spec: "SPEC-{4-digit sequential}"
  plan: "PLAN-{4-digit sequential}"
  task: "TASK-{4-digit sequential}"
  run: "RUN-{4-digit sequential}"
  fail: "FAIL-{4-digit sequential}"
  merge: "PR number from GitHub"

# --- Anti-Pattern Detection Thresholds ---
anti_pattern_detection:
  big_bang_prompt:
    signal: "Single commit touching >20 files without TASK-ID"
    max_files_per_commit: 20
  vibe_merge:
    signal: "PR merged without any quality gate passing"
  silent_scope_expansion:
    signal: "Changes to files outside TASK File Scope"
  invisible_development:
    signal: "Commits without TASK-ID in message"

# --- Harness Configuration ---
harness:
  max_iterations: 5               # Execute-Verify loop limit
  spec_score_threshold: 100        # Phase 1: Evaluator score to proceed
  plan_score_threshold: 100        # Phase 2: Evaluator score to proceed
  review_score_threshold: 100      # Phase 3-4: Review Agent score to pass
  # 100未満 → verdict: FAIL → fix_scope に従いエージェント再実行
  # Hard Fail → retry_allowed: false → 即abort
  spec_eval_max_iterations: 10     # Phase 1: Evaluator loop limit
  plan_eval_max_iterations: 10     # Phase 2: Evaluator loop limit
  verify_pass_required: true       # All gates must pass
  enable_browser_verify: false     # Playwright MCP browser verification
  # abort_reason values: max_iterations | same_fail_3x | spec_eval_max | plan_eval_max | human_escalation | yaml_schema_error
  # Failure accumulation (Knowledge Management)
  auto_append_failures: true       # Auto-append Verify Fail patterns to sage/failures.md
  same_fail_abort_threshold: 3     # Abort on same CHECK-ID failing 3 times consecutively
  failure_pattern_escalation: 3    # Escalate to sage/anti-patterns.md after 3 occurrences

# --- Project Checks (SPEC-0002: Gate Enforcement) ---
# Configure language-specific commands for CI gates.
# Uncomment and set commands for your project.
# If unset, the corresponding gate check will be SKIPPED (not faked as PASS).
project_checks:
  # lint: "npm run lint"                    # Gate 1: Lint check
  # format: "npx prettier --check ."       # Gate 1: Format check
  # type_check: "npx tsc --noEmit"         # Gate 1: Type check
  # test_command: "npm test"               # Gate 2: Test runner
  # Go example:
  #   lint: "golangci-lint run"
  #   format: "gofmt -l . | grep -c . && exit 1 || true"
  #   type_check: "go vet ./..."
  #   test_command: "go test ./... -coverprofile=coverage.out"
  # Python example:
  #   lint: "ruff check ."
  #   format: "black --check ."
  #   type_check: "mypy ."
  #   test_command: "pytest --cov=src --cov-report=term-missing"

# --- Hooks (SPEC-0003: Hooks実用化) ---
# Profile controls which hooks are active.
# Aligned with SAGE adoption phases:
#   minimal  = Phase A (SessionStart + Stop only)
#   standard = Phase B (+ dangerous command block + SAGE file protection)
#   strict   = Phase C+ (+ File Scope check as block)
#   none     = All hooks disabled
hooks:
  profile: minimal
  # Upgrade conditions:
  #   minimal → standard: make report shows SESSIONS >= 10 and STATUS: HEALTHY
  #   standard → strict:  make report shows 2 weeks continuous HEALTHY

# --- Auto Update ---
auto_update:
  installer_url: "https://gist.githubusercontent.com/YOUR_USER/GIST_ID/raw/install.sh"
  check_interval: "daily"

__EOF_TMPL_CONFIG__

read -r -d '' TMPL_CLAUDE_SNIPPET <<'__EOF_TMPL_CLAUDE_SNIPPET__' || true

<!-- === SAGE Development System (auto-injected) === -->
## SAGE Development System

- Before writing ANY code, check `specs/` for an existing SPEC. No SPEC = no code.
- Only modify files listed in the active TASK's File Scope.
- Every commit must include a TASK-ID (enforced by pre-commit hook).
- Prototypes go on `vibe/*` branches (no SPEC needed).
- For detailed workflows: `/sage-spec`, `/sage-plan`, `/sage-review`, `/sage-evaluate`
- SPEC/PLAN completion triggers auto-scoring (100 points required before implementation).
- Governance docs in `sage/` — do not modify without human approval.
- Run `bash scripts/sage-update-check.sh` at session start (1日1回).

Auto-update rules:
- Update check failure → warning only, never block development
- `installer_url` not configured → skip silently

Project-specific rules: add your own files to `.claude/rules/` (do not edit `specs-rules.md` etc. — they are overwritten on update).

Directory: `specs/` (what) | `plans/` (how) | `tasks/` (work units) | `sage/` (governance)
<!-- === End SAGE === -->

__EOF_TMPL_CLAUDE_SNIPPET__

read -r -d '' TMPL_AGENTS_SNIPPET <<'__EOF_TMPL_AGENTS_SNIPPET__' || true

<!-- === SAGE Development System (auto-injected) === -->
# SAGE Workflow

- Check `specs/` before writing ANY code. No SPEC = no code.
- Create SPECs using `specs/_template.md`. Minimum: scope, out-of-scope, 3 acceptance criteria.
- Create tasks in `tasks/` with explicit File Scope (which files you may modify).
- Only modify files in the TASK's File Scope.
- Every commit must include a TASK-ID (e.g., `TASK-0001: add login endpoint`).
- Prototypes go on `vibe/*` branches (no SPEC needed).
- Do not modify `sage/` without human approval.

Prohibited:
- Implementing without a SPEC
- Modifying files outside TASK's File Scope
- Leaving TODO/FIXME in committed code
- Skipping tests

Directory: `specs/` (what) | `plans/` (how) | `tasks/` (work units) | `sage/` (governance)
<!-- === End SAGE === -->

__EOF_TMPL_AGENTS_SNIPPET__

read -r -d '' TMPL_COMMIT_HOOK <<'__EOF_TMPL_COMMIT_HOOK__' || true
#!/bin/bash
# SAGE pre-commit hook: Require TASK-ID in commit messages
# Installed by sage-adopt.sh

COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Allow merge commits, rebases, and amends
if echo "$COMMIT_MSG" | grep -qE "^(Merge|Revert|fixup!|squash!)"; then
  exit 0
fi

# Allow vibe/* branch commits (no SPEC required for prototypes)
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
if echo "$BRANCH" | grep -qE "^vibe/"; then
  exit 0
fi

# Check for TASK-ID pattern
if ! echo "$COMMIT_MSG" | grep -qE "TASK-[0-9]{4}"; then
  echo ""
  echo "  SAGE: commit message must include a TASK-ID"
  echo "  Example: TASK-0001: add login endpoint"
  echo ""
  echo "  If this is a prototype, use a vibe/* branch."
  echo ""
  exit 1
fi

__EOF_TMPL_COMMIT_HOOK__

read -r -d '' TMPL_RULES_SPECS <<'__EOF_TMPL_RULES_SPECS__' || true
---
description: "SAGE rules for creating and editing specifications"
globs: ["specs/**"]
---
# Spec Rules

When creating or editing files in specs/:

## Required fields (all mandatory)
- SPEC-ID: assigned via `bash scripts/sage-id-gen.sh spec`
- Background/purpose: at least one sentence explaining why
- Scope (included): bullet list of what changes
- Scope (excluded): explicit exclusions. "None" is never acceptable
- Acceptance criteria: minimum 3, each verifiable by command or test
- Error cases: minimum 1 defined
- Security requirements: stated, or reason why N/A

## Exit criteria checklist
- [ ] SPEC-ID assigned
- [ ] Background described
- [ ] Scope listed as bullets
- [ ] Out-of-scope explicitly stated
- [ ] 3+ acceptance criteria, each command-verifiable
- [ ] 1+ error case
- [ ] Security requirements stated

## Prohibited
- Approving a spec with "TBD" or "TODO" in required fields
- Skipping the out-of-scope section
- Acceptance criteria that cannot be verified by command or test

## Template
Use `specs/_template.md` as the base for all new specs.

__EOF_TMPL_RULES_SPECS__

read -r -d '' TMPL_RULES_PLANS <<'__EOF_TMPL_RULES_PLANS__' || true
---
description: "SAGE rules for creating implementation plans"
globs: ["plans/**"]
---
# Plan Rules

When creating or editing files in plans/:

## Required fields
- PLAN-ID: linked to a SPEC-ID
- Affected layers: list all (controller/usecase/domain/infrastructure etc.)
- Impact scope: identified by feature/module
- Risks: at least 1 raised
- Verification: specify required methods (unit/integration/e2e/security)

## Exit criteria checklist
- [ ] PLAN-ID linked to SPEC-ID
- [ ] Affected layers listed
- [ ] Impact scope identified
- [ ] 1+ risk raised
- [ ] Verification methods specified

## Prohibited
- Creating a plan without an approved SPEC
- Starting implementation without an approved plan

## Template
Use `plans/_template.md` as the base.

__EOF_TMPL_RULES_PLANS__

read -r -d '' TMPL_RULES_TASKS <<'__EOF_TMPL_RULES_TASKS__' || true
---
description: "SAGE rules for task definitions"
globs: ["tasks/**"]
---
# Task Rules

When creating or editing files in tasks/:

## Required fields
- TASK-ID: assigned via `bash scripts/sage-id-gen.sh task`
- Single responsibility: one task does one thing (no spanning layers or purposes)
- File Scope: explicit list of files allowed to modify
- Dependencies: list dependent TASK-IDs or state "none"
- Completion criteria: defined by test pass/fail

## Exit criteria checklist
- [ ] TASK-ID assigned
- [ ] Single responsibility maintained
- [ ] File Scope explicitly listed
- [ ] Dependencies stated
- [ ] Parallel feasibility evaluated
- [ ] Completion criteria defined

## Prohibited
- Combining multiple responsibilities in one task
- Omitting File Scope (every task must state which files it may touch)

## Template
Use `tasks/_template.md` as the base.

__EOF_TMPL_RULES_TASKS__

read -r -d '' TMPL_RULES_SRC <<'__EOF_TMPL_RULES_SRC__' || true
---
description: "SAGE rules for source code implementation"
globs: ["src/**", "app/**", "lib/**", "components/**", "packages/**"]
---
# Implementation Rules

When writing or modifying source code:

## Before coding
- Confirm a SPEC and TASK exist for this change
- Check the TASK's File Scope — only modify listed files
- Include TASK-ID in every commit message (e.g., `TASK-0001: add endpoint`)

## Forbidden shortcuts
- TODO/FIXME in committed code
- Type assertions (`as unknown as T`) without explicit approval
- Bypassing quality gates (including force push)
- Changes outside assigned File Scope
- Silent scope expansion (adding unspecified changes)

## Before starting
実装開始前に `sage/failures.md` を確認し、過去に同様のパターンで失敗していないか確認すること。

## Code readability and maintainability

コードは正しく動くだけでなく、他の開発者（人間・AI問わず）が読んで理解・保守できることを重視する。コミット前に以下を確認すること:

### Intentional changes only
- 変更ブロックごとにTASK目的との対応を説明できるか。説明できない追加・変更は削除する
- 変更対象外の行に差分が出ていないか（trailing whitespace、行末改行の変更等）

### Consistency with existing code
- 同ファイル・同モジュール内に同等の処理パターンがある場合、既存のパターン・命名・記法に合わせる
- 既存パターンと異なる書き方をする場合は、改善の理由を説明できること（既存が悪い場合は改善してよい）

### Readable intent
- 非自明な制御フロー（early return、条件分岐、例外処理）の意図がコードだけで伝わらない場合、コメントで補足する
- 関数のインターフェース設計に一貫性を持たせる（条件分岐に使う値の一部だけを引数にして残りを外部依存にしない）

### No speculative code
- 「念のため」や「将来使うかもしれない」コードを追加しない
- 追加するコードは全て、現在のTASKの完了に必要な理由を説明できること

## Error resolution protocol
When an error occurs:
1. Record the error with TASK-ID in the run log
2. Check `sage/anti-patterns.md` for known patterns
3. If new pattern, add to `sage/failures.md` before fixing
4. If same error occurs 3 times, escalate to `sage/anti-patterns.md`

Error context (always include these 6 elements):
1. Error log: complete stack trace
2. Failing file: path and line number
3. Related spec: SPEC-ID and relevant acceptance criteria
4. Recent changes: git diff output
5. Fix scope: files allowed to modify
6. Completion criteria: test pass/fail

## Error resolution prohibitions
| Prohibited | Required |
|-----------|----------|
| Suppress types with `any` | Fix the type mismatch properly |
| Modify tests to make them pass | Fix implementation to pass existing tests |
| Adjust code to absorb spec drift | Update spec first, then fix implementation |
| Swallow errors with try/catch | Log the error, then re-throw |

__EOF_TMPL_RULES_SRC__

read -r -d '' TMPL_RULES_GOVERNANCE <<'__EOF_TMPL_RULES_GOVERNANCE__' || true
---
description: "SAGE governance protection rules"
globs: ["sage/**", "CLAUDE.md", "AGENTS.md"]
---
# Governance Rules

## Protected files
- `sage/` directory: human approval required for any modification
- `CLAUDE.md`: human-only (AI must not modify without explicit instruction)
- `AGENTS.md`: same as CLAUDE.md

## Agent separation
- The same agent MUST NOT hold both implementation and final approval
- The same agent MUST NOT hold both implementation and security approval
- Implementation and review must be in separate sessions

## Traceability
Every change must be traceable: SPEC-ID → PLAN-ID → TASK-ID → commit
- All PRs must include SPEC-ID, PLAN-ID, TASK-ID in the body
- All commit messages must include TASK-ID
- PRs without SPEC-ID should be rejected

## Language rules
| Context | Language |
|---------|----------|
| User-facing documentation | Japanese |
| Code, comments, variable names | English |
| Commit messages | English |
| PR descriptions | Japanese |
| Test case names | Japanese |

__EOF_TMPL_RULES_GOVERNANCE__

read -r -d '' TMPL_SKILL_SPEC <<'__EOF_TMPL_SKILL_SPEC__' || true
---
name: sage-spec
description: "Create a SAGE specification document with the user"
---

# SAGE Spec Creation Workflow

## When to use
When a new feature, bug fix, or refactor needs a specification.

## Process

### 1. Generate SPEC-ID
```bash
bash scripts/sage-id-gen.sh spec
```

### 2. Create spec file
Copy `specs/_template.md` to `specs/SPEC-{ID}-{short-name}.md`

### 3. Fill sections with the user
Work through each section interactively:

- **Background/purpose**: Why does this change exist?
- **Scope (included)**: What exactly changes? (bullet list)
- **Scope (excluded)**: What is NOT changing? ("None" is never acceptable)
- **Acceptance criteria**: Minimum 3, each must be verifiable by command or test
- **Error cases**: Minimum 1
- **Security requirements**: State them, or explain why N/A

### 4. Validate exit criteria
- [ ] SPEC-ID assigned
- [ ] Background described (>=1 sentence)
- [ ] Scope listed as bullets
- [ ] Out-of-scope explicitly stated
- [ ] 3+ acceptance criteria, each command-verifiable
- [ ] 1+ error case defined
- [ ] Security requirements stated

### Minimal spec example
```markdown
# SPEC-XXXX: Fix login button not responding

## Scope
- Fix click handler on LoginButton component

## Out of scope
- Login flow redesign
- Password reset

## Acceptance criteria
1. Clicking login button submits the form
2. Error message appears on invalid credentials
3. Existing tests pass
```

## File scope for this skill
- Write: `specs/`
- Read: `plans/`, `sage/governance.md`
- Forbidden: `src/`, `tests/`, `.github/`

## After completion
Automatically run `/sage-evaluate` to score the SPEC.
The evaluate skill will loop up to 10 times, improving the SPEC until it reaches 100 points (S++).
Only after 100 points is achieved, tell the user: "Spec ready. Next: create a plan with `/sage-plan`"

__EOF_TMPL_SKILL_SPEC__

read -r -d '' TMPL_SKILL_PLAN <<'__EOF_TMPL_SKILL_PLAN__' || true
---
name: sage-plan
description: "Create a SAGE implementation plan and task breakdown"
---

# SAGE Plan & Task Creation Workflow

## When to use
After a SPEC is approved. Creates a PLAN and breaks it into TASKs.

## Process

### Phase 1: Create Plan
1. Generate PLAN-ID: `bash scripts/sage-id-gen.sh plan`
2. Copy `plans/_template.md` to `plans/PLAN-{ID}.md`
3. Link to the source SPEC-ID
4. Identify affected architectural layers (controller/usecase/domain/infrastructure etc.)
5. Assess impact scope by feature/module
6. Raise at least 1 risk
7. Specify verification methods (unit/integration/e2e/security)

### Phase 2: Slice into Tasks
1. Generate TASK-IDs: `bash scripts/sage-id-gen.sh task` (one per task)
2. Each TASK must have:
   - Single responsibility (does not span layers or purposes)
   - Explicit File Scope (list of files allowed to modify)
   - Dependencies (list dependent TASK-IDs or "none")
   - Completion criteria (test pass/fail)
3. Evaluate parallel feasibility per task
4. Draw dependency graph if tasks > 3

### Plan exit criteria
- [ ] PLAN-ID linked to SPEC-ID
- [ ] Affected layers listed
- [ ] Impact scope identified
- [ ] 1+ risk raised
- [ ] Verification methods specified

### Slice exit criteria
- [ ] All TASKs have TASK-IDs
- [ ] Single responsibility per TASK
- [ ] File Scope explicitly listed per TASK
- [ ] Dependencies stated
- [ ] Parallel feasibility evaluated
- [ ] Completion criteria per TASK

## File scope for this skill
- Write: `plans/`, `tasks/`
- Read: `specs/`
- Forbidden: `src/`, `tests/`, `sage/`

## After completion
Automatically run `/sage-evaluate` to score the PLAN and TASKs.
The evaluate skill will loop up to 10 times, improving the documents until they reach 100 points (S++).
Only after 100 points is achieved, tell the user: "Plan and tasks ready. Implementation can begin on separate sessions."

__EOF_TMPL_SKILL_PLAN__

read -r -d '' TMPL_SKILL_REVIEW <<'__EOF_TMPL_SKILL_REVIEW__' || true
---
name: sage-review
description: "Review code changes against SAGE spec and quality gates"
---

# SAGE Code Review Workflow

## When to use
After implementation. Must be in a SEPARATE session from implementation.

## Review checklist (in order)

### 1. Spec Alignment
- Does the code match the SPEC's acceptance criteria?
- Are there changes not covered by the SPEC? (= Silent Scope Expansion)

### 2. Scope Compliance
- Do changes stay within the TASK's File Scope?
- Flag any files modified that are not in the TASK definition

### 3. Responsibility Alignment
- Single responsibility per TASK maintained?
- Layer boundaries respected?

### 4. Complexity
- Unnecessary abstractions or over-engineering?
- Could the same result be achieved more simply?

### 5. Test Adequacy
- Normal, boundary, and error cases covered?
- Coverage above threshold (default 80% per .sage/config.yaml)?

### 6. Safety
- No hardcoded secrets or credentials
- Input validation at system boundaries
- Dependencies up to date and secure

### 7. Code Quality
コードが「動く」だけでなく「読みやすく保守しやすい」かを確認:
- **変更の意図性**: 各変更ブロックにTASK目的との対応があるか。目的を説明できない追加・変更がないか
- **既存コードとの一貫性**: 同ファイル内の既存パターンと異なる記法・命名がある場合、改善の理由が説明できるか
- **インターフェース設計**: 関数の引数設計に一貫性があるか（同種の値が引数と外部依存に分散していないか）
- **セルフレビュー遵守**: src-rules の「Code readability and maintainability」が実際に守られているか

## Quality gates to verify
| Gate | Checks |
|------|--------|
| 1. Structural | lint, format, type check |
| 2. Functional | tests pass, coverage >= threshold |
| 3. Security | secret scan, dependency vuln scan |
| 4. Architecture | layer boundary, traceability (SPEC->PLAN->TASK->commit) |
| 5. Release | migration safety, rollback readiness |

## Anti-patterns to flag
Reference: `sage/anti-patterns.md`
- Vibe Merge: PR merged without gate pass
- Big Bang Prompt: single commit >20 files without TASK-ID
- Silent Scope Expansion: changes outside File Scope
- Invisible Development: no TASK-ID in commits

## Rules
- This review MUST be in a separate session from implementation
- Never approve changes that fail quality gates
- Never approve changes outside TASK's File Scope
- Flag new anti-patterns for `sage/anti-patterns.md`

## After review
レビューで新しい品質問題パターンを発見した場合、`sage/failures.md` に症状/原因/対策/検出層の4項目で追記すること。

---

## Scoring Rubric（コードレビュー採点基準）

| 軸 | 満点 | 評価観点 |
|----|------|---------|
| Spec Alignment | 25点 | SPECの受け入れ条件との一致。Silent Scope Expansionの有無 |
| Scope Compliance | 20点 | TASK File Scope内のみ変更。違反は即Hard Fail |
| Responsibility Alignment | 15点 | 単一責任維持。レイヤー境界遵守 |
| Complexity | 10点 | 不要な抽象化・過度な結合がないか |
| Test Adequacy | 15点 | 正常系・境界値・異常系カバレッジ。閾値達成 |
| Safety | 15点 | secrets/credentials検出なし。入力バリデーション。依存脆弱性なし |

合計: 100点

詳細な満点条件と減点トリガーは `references/review-scoring-rubric.md` を参照。

### Hard Fail条件（点数に関係なく即FAIL）

以下のいずれかに該当する場合、スコアに関係なく `verdict: FAIL` + `retry_allowed: false`:

- **File Scope違反**: TASK File Scope外のファイルを変更
- **Gate 1-4のいずれかFail**: Structural / Functional / Security / Architecture
- **secrets/credentialsのハードコード**: APIキー、パスワード、トークン等
- **既知脆弱性を持つ依存の追加**: CVEが報告されている依存パッケージ

---

## 出力フォーマット（review_feedback YAML）

レビュー結果を以下の構造化 YAML で返却する：

```yaml
review_feedback:
  round: N
  iteration: M
  verdict: PASS | FAIL
  review_score: N
  subscores:
    spec_alignment: N/25
    scope_compliance: N/20
    responsibility_alignment: N/15
    complexity: N/10
    test_adequacy: N/15
    safety: N/15
  gate_results:
    structural: pass | fail
    functional: pass | fail
    security: pass | fail
    architecture: pass | fail
  findings:
    - id: "REV-001"
      category: "spec_alignment | scope_compliance | responsibility | complexity | test | safety"
      severity: "critical | major | minor"
      file: "path/to/file"
      expected: "期待される状態"
      actual: "現在の状態"
  fix_scope:
    implementation: [{ file, reason }]
    test: [{ file, reason }]
  instruction:
    - target: "implementation"
      action: "Implementation Agentへの具体的修正指示"
    - target: "test"
      action: "Test Agentへの具体的修正指示"
  retry_allowed: true | false
  same_fail_count: N
```

---

## File scope for this skill
- Read: all files
- Write: NONE（review_feedback YAML を出力として返すのみ。コード修正は行わない）

__EOF_TMPL_SKILL_REVIEW__

read -r -d '' TMPL_SKILL_EVALUATE <<'__EOF_TMPL_SKILL_EVALUATE__' || true
---
name: sage-evaluate
description: "SAGE要件定義・プラン自動採点スキル: SPEC/PLANを6軸・100点満点で採点し、構造化フィードバックを返す。修正はCreator Agentの責務。MANDATORY TRIGGERS: プランを評価, SPECを評価, 採点して, evaluate, score plan, score spec"
---

# SAGE 要件定義・プラン自動採点スキル

SAGE の SPEC / PLAN / TASK を、AI駆動開発のベストプラクティスに基づいて採点し、**構造化フィードバック（eval_feedback YAML）を返す** Read-Only 採点スキル。修正は Creator Agent（Spec Agent / Planning Agent）の責務であり、本スキルはドキュメントを一切変更しない。

## 採点の背景

このスキルは以下の知識を評価軸として使用する：

1. **SAGE Development System** — Spec-driven, Agent-governed, Guard-railed, Evolving
2. **ai-development-patterns** — SPEC-IDトレーサビリティ・failures.md蓄積
3. **awesome-AIDD** — TDD Guard・cc-sddワークフロー
4. **auto-dev** — Error Recovery・Observable Development
5. **SoftwareSeni SDD** — 仕様書品質基準・5本柱検証

詳細な知識ベースは `references/knowledge-base.md` を参照。

---

## 評価フロー（Read-Only）

本スキルは **採点 → 構造化フィードバック返却** のみを行う。改善ループの制御はオーケストレーター（sage-harness）が担当する。

```
┌─────────────────────────────────────────┐
│  1. SPEC/PLAN/TASK を読み込む            │
│  2. 6軸で採点する                        │
│  3. eval_feedback YAML を返却する        │
│     → ループ制御はオーケストレーターが行う │
└─────────────────────────────────────────┘
```

### Read-Only ルール
- **ドキュメントの修正は一切行わない**（Write/Edit ツール使用禁止）
- 問題を発見した場合は `findings` + `fix_instructions` として報告する
- 修正の実行は Creator Agent（Spec Agent / Planning Agent）の責務

---

## 採点手順

### Step 1: ドキュメントを読む

対象ファイルを読み、以下を把握する：
- SPEC: スコープ・除外範囲・受け入れ条件・エラーケース
- PLAN: 影響層・リスク・検証方法
- TASK: 単一責任・File Scope・依存関係・完了条件

### Step 2: 6軸で採点する

各軸を採点し、合計点を算出する。詳細な採点基準は `references/scoring-rubric.md` を参照。

| 軸 | 満点 | 評価観点 |
|----|------|---------|
| ① Codified Rules | 20点 | CLAUDE.md連携・Forbidden Shortcuts・機械的ゲート |
| ② Atomic Decomposition | 20点 | タスクの独立性・依存グラフ・完了条件の明確さ |
| ③ Spec-Driven Development | 20点 | SPEC-ID・受け入れ条件の具体性・エラーケース |
| ④ Observable Development | 20点 | 検証コマンド・フィードバックループ・計測方法 |
| ⑤ Knowledge Management | 15点 | failures.md連携・Error Resolution・知識蓄積 |
| ⑥ 段階採用戦略 | 5点（加点） | 既存コード影響ゼロ・段階的導入設計 |

### Step 3: 出力フォーマット（eval_feedback YAML）

採点結果を以下の構造化 YAML で返却する：

```yaml
eval_feedback:
  target_file: "specs/SPEC-XXXX-*.md"
  target_type: SPEC | PLAN | TASK
  verdict: PASS | FAIL
  total_score: N
  grade: "S++ | S+ | S | A- | B | C"
  subscores:
    codified_rules: N/20
    atomic_decomposition: N/20
    spec_driven_development: N/20
    observable_development: N/20
    knowledge_management: N/15
    gradual_adoption: N/5
  findings:
    - id: "EVAL-001"
      axis: "codified_rules"
      severity: "critical | major | minor"
      location: "セクション名"
      problem: "問題の1行説明"
      expected: "期待される記述"
      actual: "現在の記述"
  fix_instructions:
    - finding_id: "EVAL-001"
      target_file: "specs/SPEC-XXXX-*.md"
      section: "File Scope"
      action: "修正内容の具体的指示"
      example: "修正例"
```

### 判定基準

- `verdict: PASS` — total_score >= 100（グレード S++）
- `verdict: FAIL` — total_score < 100（fix_instructions を参照して修正が必要）

---

## グレード基準

| スコア | グレード | 判定 |
|--------|---------|------|
| 100 | S++ | 完璧。即実装可。verdict: PASS |
| 95-99 | S+ | ほぼ完成。微修正で到達可能 |
| 90-94 | S | 優秀。小改善あり |
| 85-89 | A- | 良好。改善推奨 |
| 70-84 | B | 基本OK。要改善 |
| ~69 | C | 大幅改善必要 |

---

## 呼び出し方

### 手動呼び出し
```
/sage-evaluate
```

### オーケストレーター経由（推奨）
`/sage-harness` 内で Evaluator として呼び出される。
オーケストレーターが eval_feedback を受け取り、verdict: FAIL の場合は Creator Agent に fix_instructions を渡して修正させ、再採点を依頼する。

---

## 評価時の注意

- 採点は厳格に行う。「書いてあれば満点」ではなく「具体性・実行可能性」で判断する
- findings は必ず実行可能な形（コマンド・コードスニペット）で fix_instructions に示す
- 「実装を止める問題」か「実装後に気づく小さな穴」かを severity で区別する
- 前バージョンがある場合は差分を明示し、改善が反映されているか確認する
- スコアが100点なら verdict: PASS を返す

---

## File scope for this skill
- Read: `specs/`, `plans/`, `tasks/`, `sage/`, `.sage/config.yaml`
- Write: NONE（採点エージェントはドキュメントを一切修正しない）
- Forbidden: `src/`, `tests/`, `.github/`, `CLAUDE.md`, `specs/`, `plans/`, `tasks/`（書き込み）

## 参照ファイル

- `references/knowledge-base.md` — 5ソースの知識ベース詳細（評価の根拠）
- `references/scoring-rubric.md` — 6軸の詳細採点基準と減点トリガー一覧

__EOF_TMPL_SKILL_EVALUATE__

read -r -d '' TMPL_SKILL_EVALUATE_RUBRIC <<'__EOF_TMPL_SKILL_EVALUATE_RUBRIC__' || true
# 6軸 詳細採点基準

## ① Codified Rules（満点20点）

### 満点条件（20点）
- CLAUDE.md / `.claude/rules/` への具体的なルール連携が定義されている
- Forbidden Shortcuts（禁止事項）が明示されている
- 機械的ゲート（lint/CI/hook）でルール違反を自動検出できる
- File Scope（修正可能ファイル）が明示されている

### 減点トリガー
| 問題 | 減点 |
|------|------|
| CLAUDE.md/rules への連携が抽象的（「適切に」「正しく」など） | -3 |
| Forbidden Shortcuts の明示がない | -3 |
| 機械的ゲート（lint/CI/hook）がない | -4 |
| File Scope が定義されていない | -4 |
| Error Resolution 手順への言及がない | -3 |
| commit-msg hook（TASK-ID必須）への言及がない | -2 |

---

## ② Atomic Decomposition（満点20点）

### 満点条件（20点）
- 各タスクが単一責任で分解されている
- 依存グラフが明示されている（A→B→C並列等）
- 各タスクの完了条件がコマンドで検証できる
- 並列実行可能なタスクが明示されている

### 減点トリガー
| 問題 | 減点 |
|------|------|
| タスクが複数レイヤーにまたがり独立していない | -4 |
| 依存グラフがない（実行順序が不明） | -4 |
| 完了条件が「目視確認」など主観的 | -4 |
| 並列実行可能かどうか不明 | -3 |
| タスクの粒度が大きすぎる（File Scope > 10ファイル） | -2 |
| TASK-IDが振られていない | -3 |

---

## ③ Spec-Driven Development（満点20点）

### 満点条件（20点）
- SPEC-IDが振られている
- 受け入れ条件が正常系・異常系の両方で書かれている
- 受け入れ条件が具体的なコマンド/テストで検証可能
- Out-of-scope（対象外）が明示されている

### 減点トリガー
| 問題 | 減点 |
|------|------|
| SPEC-IDがない | -5 |
| 受け入れ条件が片方向のみ（正常系のみ、または異常系のみ） | -3 |
| 受け入れ条件がコマンドで検証できない | -4 |
| Out-of-scope（対象外）が「なし」または未記載 | -3 |
| タスクの記述が3行以下で具体性が著しく低い | -3 |
| セキュリティ要件への言及がない | -2 |

---

## ④ Observable Development（満点20点）

### 満点条件（20点）
- 各フェーズに具体的な検証コマンドがある
- テスト種別（unit/integration/e2e）が明示されている
- フィードバックサイクルが明文化されている
- 検証方法セクションに具体的な手順がある

### 減点トリガー
| 問題 | 減点 |
|------|------|
| 検証方法が「目視確認」のみ | -5 |
| フェーズごとの検証コマンドがない | -4 |
| テスト種別（unit/integration/e2e）の指定がない | -3 |
| カバレッジ閾値への言及がない | -3 |
| Quality Gate（5段階）との対応が不明 | -2 |
| 本番→開発へのフィードバックループがない | -2 |

---

## ⑤ Knowledge Management（満点15点）

### 満点条件（15点）
- `sage/failures.md` との連携が設計されている
- Error Resolution 手順がある（エラー時に何をするか）
- `sage/anti-patterns.md` の参照がある
- 新規パターン発見時の蓄積フローがある

### 減点トリガー
| 問題 | 減点 |
|------|------|
| failures.md への言及がない | -4 |
| Error Resolution 手順がない | -4 |
| anti-patterns.md の参照がない | -2 |
| 新規失敗パターンの蓄積フローがない | -2 |
| リスクが1つも挙げられていない | -3 |

---

## ⑥ 段階採用戦略（加点最大5点）

### 加点条件
- 既存コードへの影響ゼロ戦略がある: +2点
- 段階的に適用できる設計がある: +1点
- ロールバック手順が明記されている: +1点
- 影響範囲が最小限に抑えられている: +1点

---

## グレード基準

| スコア | グレード | 判定 |
|--------|---------|------|
| 100 | S++ | 完璧。即実装可。「このまま実装を開始してください」と明示 |
| 95-99 | S+ | ほぼ完成。微修正で到達可能 |
| 90-94 | S | 優秀。小改善あり。改善後に実装推奨 |
| 85-89 | A- | 良好。改善推奨。改善してから実装 |
| 70-84 | B | 基本OK。要改善。改善必須 |
| ~69 | C | 大幅改善必要。実装前に再設計 |

---

## 修正指示の優先順位（fix_instructions）

スコアが低い場合、以下の順で修正を指示する（効果が大きいものから）：

| 優先度 | 修正内容 | 典型的な効果 |
|--------|---------|------------|
| 1 | SPEC-ID / TASK-ID の付与 | +5〜8点 |
| 2 | 受け入れ条件の具体化（コマンド追加） | +4〜7点 |
| 3 | Out-of-scope の明示 | +3点 |
| 4 | 依存グラフの追加 | +4点 |
| 5 | File Scope の明示 | +4点 |
| 6 | Error Resolution 手順の追加 | +4点 |
| 7 | 検証コマンドの追加 | +4点 |
| 8 | failures.md / anti-patterns.md 連携 | +4〜6点 |
| 9 | リスクの追加 | +3点 |
| 10 | セキュリティ要件の追加 | +2点 |

__EOF_TMPL_SKILL_EVALUATE_RUBRIC__

read -r -d '' TMPL_SKILL_EVALUATE_KB <<'__EOF_TMPL_SKILL_EVALUATE_KB__' || true
# 知識ベース：評価の根拠となる5ソース

採点の根拠となるソースから抽出した核心知識。

---

## ① SAGE Development System

### 7フェーズ ライフサイクル
```
Specify → Plan → Slice → Execute → Verify → Merge → Observe
```
各フェーズに Exit Criteria（終了条件）があり、すべて満たさないと次に進めない。

### Forbidden Shortcuts（AIへの絶対禁止）
- TODO/FIXME をコミットに残す
- `as unknown as T` 等の型アサーションを無断で使う
- Quality Gate をバイパスする（force push含む）
- SPEC-ID なしの PR を作る
- File Scope 外のファイルを変更する
- 同一セッションで実装とレビューを兼ねる

### トレーサビリティチェーン
```
SPEC-ID → PLAN-ID → TASK-ID → commit → PR → merge
```
すべてのコミットに TASK-ID が必要。PR には SPEC-ID, PLAN-ID, TASK-ID が必要。

### Quality Gate（5段階）
| Gate | チェック |
|------|---------|
| 1. Structural | lint, format, type check |
| 2. Functional | unit test, integration test, coverage |
| 3. Security | SAST, secret scan, dependency vuln |
| 4. Architecture | layer boundary, traceability |
| 5. Release | migration safety, rollback readiness |

---

## ② ai-development-patterns

### SPEC-ID トレーサビリティ
要件→テスト→コードの双方向追跡。

```
SPEC-0001: ログインボタンが反応しない問題を修正
// Implements: SPEC-0001
function handleLoginClick() { ... }
```

SPEC-IDがない場合の問題:
- CIで要件充足を自動確認不可
- リグレッション影響範囲の特定困難
- レビュー時にSPECとの整合性を確認できない

### failures.md パターン
AIが同じミスを繰り返さないよう失敗事例を蓄積する。

```markdown
## FAIL-001: 型エラーを any で握りつぶした
- 発生条件: 複雑な型推論が必要なケースで発生
- 対策: 型を正しく定義する。any は使わない
- 再発防止: ESLint の no-explicit-any ルールで機械的に検出
```

### Codified Rules の設計
CLAUDE.md（中央司令塔）→ `.claude/rules/`（パス別詳細）
ルールは「書いてある」だけでなく「機械で検出できる」ことが重要。

---

## ③ awesome-AIDD

### 即効性のある改善パターン
| パターン | 効果 |
|---------|------|
| TDD Guard | テストなし実装をコミット時に自動ブロック |
| cc-sdd | requirements→design→tasks ワークフローを強制 |
| Guardrails | 誤ブランチへのコミット防止・自動チェックポイント |
| pr-agent | PRのAI自動レビュー |

### 品質ゲートの自動化
手動レビューに頼る部分を可能な限り CI/hook で自動化する。
「ルールがある」と「ルールが強制される」は別物。

---

## ④ auto-dev

### Error Resolution手順
```
1. エラーログを確認し、TASK-ID を記録
2. sage/anti-patterns.md の該当パターンを参照
3. 新規パターンなら sage/failures.md に追記
4. 修正スコープを File Scope 内に限定
5. 完了条件: テスト Pass + 型エラー増加なし
6. 同じエラーが3回発生したら anti-patterns.md に昇格
```

### Observable Development
```
エラー発生 → run log に記録 → failures.md に追記
  → CLAUDE.md/rules から参照 → 次のAIが同じミスをしない
```

観測可能性のキー: すべてのエージェント実行が RUN-ID で追跡可能。

---

## ⑤ SoftwareSeni SDD

### 仕様書の品質基準
| 対象 | 推奨長さ |
|------|---------|
| バグ修正 SPEC | 100-200語 |
| 機能追加 SPEC | 300-500語 |
| アーキテクチャ変更 SPEC | 500-1000語 |
| システム設計 PLAN | 1000-2000語 |

### バイブコーディング vs 仕様駆動
- 探索・PoC・プロトタイプ → `vibe/*` ブランチ（SPEC不要）
- 本番実装・チーム開発 → SAGE ワークフロー（SPEC必須）

### 5本柱の品質ゲート
1. セキュリティ（SAST・シークレット検出）
2. テスト（カバレッジ閾値・E2E）
3. コード品質（Linting・複雑度）
4. パフォーマンス（レスポンスタイム・DBクエリ）
5. デプロイ準備（設定管理・ロギング）

### 現実的な期待値
- 学習段階でデバッグ時間増加は正常（67%の開発者が経験）
- 生産性向上の実感: 約11週間後
- ROIタイムライン: 3〜6ヶ月

__EOF_TMPL_SKILL_EVALUATE_KB__

read -r -d '' TMPL_VALIDATE <<'__EOF_TMPL_VALIDATE__' || true
#!/bin/bash
# sage-validate.sh — SAGE構造検証スクリプト
# CLAUDE.mdの必須セクション存在確認 + テンプレートフィールド検証
set -euo pipefail

ERRORS=0

echo "=== SAGE Validation ==="
echo ""

# --- CLAUDE.md Section Check ---
echo "[1/7] CLAUDE.md 必須セクション検証..."
REQUIRED_SECTIONS=(
  "Project Overview"
  "Instruction Priority"
  "SAGE Lifecycle Protocol"
  "Forbidden Shortcuts"
  "Error Resolution Protocol"
  "Agent Constraints"
  "File Scope Rules"
  "Traceability Requirements"
  "Quality Gate Checklist"
  "Language Rules"
)

if [ ! -f CLAUDE.md ]; then
  echo "  ERROR: CLAUDE.md が存在しません"
  ERRORS=$((ERRORS + 1))
else
  for section in "${REQUIRED_SECTIONS[@]}"; do
    if grep -q "$section" CLAUDE.md; then
      echo "  OK: $section"
    else
      echo "  MISSING: $section"
      ERRORS=$((ERRORS + 1))
    fi
  done
fi
echo ""

# --- specs/_template.md Field Check ---
echo "[2/7] テンプレート必須フィールド検証..."

if [ -f specs/_template.md ]; then
  REQUIRED_SPEC_FIELDS=("スコープ外" "受け入れ条件" "異常系" "契約" "リスク" "PLAN-ID")
  for field in "${REQUIRED_SPEC_FIELDS[@]}"; do
    if grep -q "$field" specs/_template.md; then
      echo "  OK: specs/_template.md → $field"
    else
      echo "  MISSING in specs/_template.md: $field"
      ERRORS=$((ERRORS + 1))
    fi
  done
else
  echo "  SKIP: specs/_template.md が存在しません"
fi

if [ -f plans/_template.md ]; then
  REQUIRED_PLAN_FIELDS=("SPEC-ID" "変更レイヤ" "影響範囲" "リスク" "タスク分解")
  for field in "${REQUIRED_PLAN_FIELDS[@]}"; do
    if grep -q "$field" plans/_template.md; then
      echo "  OK: plans/_template.md → $field"
    else
      echo "  MISSING in plans/_template.md: $field"
      ERRORS=$((ERRORS + 1))
    fi
  done
else
  echo "  SKIP: plans/_template.md が存在しません"
fi

if [ -f tasks/_template.md ]; then
  REQUIRED_TASK_FIELDS=("SPEC-ID" "PLAN-ID" "File Scope" "禁止事項" "完了条件" "RUN-ID")
  for field in "${REQUIRED_TASK_FIELDS[@]}"; do
    if grep -q "$field" tasks/_template.md; then
      echo "  OK: tasks/_template.md → $field"
    else
      echo "  MISSING in tasks/_template.md: $field"
      ERRORS=$((ERRORS + 1))
    fi
  done
else
  echo "  SKIP: tasks/_template.md が存在しません"
fi
echo ""

# --- Directory Structure Check ---
echo "[3/7] ディレクトリ構造検証..."
REQUIRED_DIRS=("specs" "plans" "tasks" "sage" ".sage" "docs" "scripts")
for dir in "${REQUIRED_DIRS[@]}"; do
  if [ -d "$dir" ]; then
    echo "  OK: $dir/"
  else
    echo "  MISSING: $dir/"
    ERRORS=$((ERRORS + 1))
  fi
done
echo ""

# --- Document Integrity Check ---
echo "[4/7] ドキュメント整合性チェック..."

# SPEC-0002: Error Context Template
if grep -q "Error Context Template" CLAUDE.md 2>/dev/null; then
  echo "  OK: CLAUDE.md → Error Context Template"
else
  echo "  MISSING: CLAUDE.md → Error Context Template"
  ERRORS=$((ERRORS + 1))
fi

# SPEC-0003: 4必須要素
if grep -q "4必須要素" sage/governance.md 2>/dev/null; then
  echo "  OK: governance.md → 4必須要素"
else
  echo "  MISSING: governance.md → 4必須要素"
  ERRORS=$((ERRORS + 1))
fi

# SPEC-0004: バイブコーディング
if grep -q "バイブコーディング" sage/governance.md 2>/dev/null; then
  echo "  OK: governance.md → バイブコーディング"
else
  echo "  MISSING: governance.md → バイブコーディング"
  ERRORS=$((ERRORS + 1))
fi

# SPEC-0005: 3層計測
if grep -q "3層計測" sage/governance.md 2>/dev/null; then
  echo "  OK: governance.md → 3層計測"
else
  echo "  MISSING: governance.md → 3層計測"
  ERRORS=$((ERRORS + 1))
fi
echo ""

# --- Vibe Branch Check ---
echo "[5/7] ブランチ規約チェック..."
CURRENT_BRANCH=${GITHUB_HEAD_REF:-$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")}
if [[ "$CURRENT_BRANCH" == vibe/* ]]; then
  echo "  ERROR: vibe/* ブランチから直接マージ禁止。staging経由 + SPEC作成後にmainへ"
  ERRORS=$((ERRORS + 1))
else
  echo "  OK: ブランチ規約準拠 (${CURRENT_BRANCH:-unknown})"
fi
echo ""

# --- Check 6: Noise Diff Check ---
echo "[6/7] ノイズ差分チェック..."
# CI環境では HEAD~1 比較、ローカルではステージング済みファイル比較
if [ -n "${CI:-}" ]; then
  DIFF_CMD="git diff HEAD~1 --check"
else
  DIFF_CMD="git diff --cached --check"
fi
NOISE=$($DIFF_CMD 2>/dev/null | grep -E "trailing whitespace|space before tab|new blank line at EOF" || true)
if [ -n "$NOISE" ]; then
  NOISE_COUNT=$(echo "$NOISE" | wc -l | tr -d ' ')
  echo "  FAIL: $NOISE_COUNT noise diff(s) detected"
  echo "  Fix: Remove trailing whitespace and unnecessary blank lines"
  ERRORS=$((ERRORS + 1))
else
  echo "  OK: ノイズ差分なし"
fi
echo ""

# --- Check 7: AI Control Plane Security Check ---
echo "[7/7] AI Control Plane セキュリティチェック..."

# Secret patterns (lightweight subset of sage-doctor.sh)
SECRET_PATTERN='(api[_-]?key|secret[_-]?key|access[_-]?token|password|credential)\s*[:=]\s*["'"'"']?[A-Za-z0-9+/=_-]{8,}'
AWS_PATTERN='(AKIA|ASIA)[A-Z0-9]{16}'
JWT_PATTERN='eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.'
GITHUB_TOKEN_PATTERN='gh[pousr]_[A-Za-z0-9_]{20,}'

SECURITY_SCAN_FILES=()
[ -f CLAUDE.md ] && SECURITY_SCAN_FILES+=("CLAUDE.md")
if [ -d ".claude/prompts" ]; then
  while IFS= read -r f; do
    SECURITY_SCAN_FILES+=("$f")
  done < <(find .claude/prompts -type f 2>/dev/null)
fi

SECRET_FOUND=false
for file in "${SECURITY_SCAN_FILES[@]}"; do
  for pattern in "$SECRET_PATTERN" "$AWS_PATTERN" "$JWT_PATTERN" "$GITHUB_TOKEN_PATTERN"; do
    if grep -qEi "$pattern" "$file" 2>/dev/null; then
      echo "  FAIL: Secret pattern detected in $file"
      ERRORS=$((ERRORS + 1))
      SECRET_FOUND=true
      break
    fi
  done
done
if [ "$SECRET_FOUND" = false ]; then
  echo "  OK: AI制御プレーンファイルにシークレットなし"
fi

# Permission check
if [ -f ".claude/settings.json" ]; then
  if grep -qE '"allow"\s*:\s*\[\s*"\*"' .claude/settings.json 2>/dev/null; then
    echo "  WARN: .claude/settings.json に過度に許可的な allow: [\"*\"] が設定されています"
  else
    echo "  OK: .claude/settings.json パーミッション適切"
  fi
fi
echo ""

# --- Summary ---
if [ $ERRORS -eq 0 ]; then
  echo "=== SAGE Validation: ALL PASSED ==="
  exit 0
else
  echo "=== SAGE Validation: $ERRORS ERROR(S) FOUND ==="
  exit 1
fi

__EOF_TMPL_VALIDATE__

read -r -d '' TMPL_ID_GEN <<'__EOF_TMPL_ID_GEN__' || true
#!/bin/bash
# sage-id-gen.sh — SPEC/PLAN/TASK ID生成
# Usage: bash scripts/sage-id-gen.sh spec|plan|task
set -euo pipefail

TYPE="${1:-}"

if [ -z "$TYPE" ]; then
  echo "Usage: bash scripts/sage-id-gen.sh <type>"
  echo "  type: spec | plan | task | run | fail"
  exit 1
fi

case "$TYPE" in
  spec)
    DIR="specs"
    PREFIX="SPEC"
    ;;
  plan)
    DIR="plans"
    PREFIX="PLAN"
    ;;
  task)
    DIR="tasks"
    PREFIX="TASK"
    ;;
  run)
    DIR=".sage/runs"
    PREFIX="RUN"
    ;;
  fail)
    DIR="sage"
    PREFIX="FAIL"
    ;;
  *)
    echo "Unknown type: $TYPE"
    echo "  Valid types: spec | plan | task | run | fail"
    exit 1
    ;;
esac

# Find the highest existing ID
LAST_NUM=0
if [ "$TYPE" = "fail" ]; then
  # Search in failures.md
  if [ -f "sage/failures.md" ]; then
    LAST_NUM=$(grep -oE "${PREFIX}-[0-9]{4}" sage/failures.md 2>/dev/null | sort -t'-' -k2 -n | tail -1 | grep -oE '[0-9]{4}' || echo 0)
  fi
else
  # Search in directory for files matching PREFIX-XXXX
  if [ -d "$DIR" ]; then
    LAST_NUM=$(ls "$DIR" 2>/dev/null | grep -oE "${PREFIX}-[0-9]{4}" | sort -t'-' -k2 -n | tail -1 | grep -oE '[0-9]{4}' || echo 0)
  fi
fi

# Remove leading zeros for arithmetic
LAST_NUM=$((10#$LAST_NUM))

# Generate next ID
NEXT_NUM=$((LAST_NUM + 1))
NEXT_ID=$(printf "${PREFIX}-%04d" "$NEXT_NUM")

echo "$NEXT_ID"

__EOF_TMPL_ID_GEN__

read -r -d '' TMPL_TRACE_CHECK <<'__EOF_TMPL_TRACE_CHECK__' || true
#!/bin/bash
# sage-trace-check.sh — トレーサビリティチェーン検証
# 直近のコミットにTASK-IDが含まれているか確認
set -euo pipefail

echo "=== SAGE Traceability Check ==="
echo ""

ERRORS=0
LIMIT=${1:-10}

echo "直近 $LIMIT コミットのTASK-ID検証..."
echo ""

while IFS= read -r line; do
  HASH=$(echo "$line" | cut -d' ' -f1)
  MSG=$(echo "$line" | cut -d' ' -f2-)

  if echo "$MSG" | grep -qE 'TASK-[0-9]{4}'; then
    echo "  OK: $HASH — $MSG"
  elif echo "$MSG" | grep -qE '^(initial commit|merge|Merge)'; then
    echo "  SKIP: $HASH — $MSG (merge/initial)"
  else
    echo "  WARN: $HASH — $MSG (TASK-ID missing)"
    ERRORS=$((ERRORS + 1))
  fi
done < <(git log --oneline -n "$LIMIT" 2>/dev/null || echo "")

echo ""

if [ $ERRORS -eq 0 ]; then
  echo "=== Traceability: ALL PASSED ==="
else
  echo "=== Traceability: $ERRORS WARNING(S) ==="
fi

__EOF_TMPL_TRACE_CHECK__

read -r -d '' TMPL_UPDATE_CHECK <<'__EOF_TMPL_UPDATE_CHECK__' || true
#!/bin/bash
# sage-update-check.sh — 1日1回、Gist から最新バージョンを確認し、必要なら自動更新
# エラーが発生しても開発を止めない（警告のみ）

SAGE_DIR=".sage"
VERSION_FILE="$SAGE_DIR/version"
LAST_CHECK_FILE="$SAGE_DIR/last-update-check"
CONFIG_FILE="$SAGE_DIR/config.yaml"

# installer_url 未設定チェック（AC-4）
if [ ! -f "$CONFIG_FILE" ]; then
  echo "SAGE: config.yaml が見つかりません。バージョンチェックをスキップします。"
  exit 0
fi

GIST_URL=$(grep 'installer_url:' "$CONFIG_FILE" 2>/dev/null | awk '{print $2}' | tr -d '"')

if [ -z "$GIST_URL" ] || echo "$GIST_URL" | grep -qF "YOUR_USER/GIST_ID"; then
  echo "SAGE: installer_url が未設定です。バージョンチェックをスキップします。"
  exit 0
fi

# 1日1回チェック制限（AC-1）
if [ -f "$LAST_CHECK_FILE" ]; then
  last_check=$(cat "$LAST_CHECK_FILE")
  today=$(date +%Y-%m-%d)
  if [ "$last_check" = "$today" ]; then
    exit 0  # 今日はチェック済み（出力なし）
  fi
fi

# 最新バージョンを取得（AC-3: curl失敗時は警告のみ）
REMOTE_VERSION=$(curl -fsSL --connect-timeout 5 "$GIST_URL" 2>/dev/null | grep -m1 'SAGE_VERSION=' | cut -d'"' -f2)

if [ -z "$REMOTE_VERSION" ]; then
  echo "SAGE: 最新バージョンの取得に失敗しました（ネットワークエラーまたはURL無効）。スキップします。"
  date +%Y-%m-%d > "$LAST_CHECK_FILE"
  exit 0
fi

LOCAL_VERSION=$(cat "$VERSION_FILE" 2>/dev/null || echo "0.0.0")

# 今日の日付を記録
date +%Y-%m-%d > "$LAST_CHECK_FILE"

# バージョン比較（AC-2）
if [ "$REMOTE_VERSION" = "$LOCAL_VERSION" ]; then
  echo "SAGE v${LOCAL_VERSION} は最新です。"
  exit 0
fi

# 自動更新（AC-5）
echo "SAGE 更新があります: v${LOCAL_VERSION} → v${REMOTE_VERSION}"
echo "更新を適用中..."

TMP_INSTALLER="/tmp/sage-install-$$-$(date +%s).sh"
if curl -fsSL --connect-timeout 10 "$GIST_URL" -o "$TMP_INSTALLER" 2>/dev/null; then
  bash "$TMP_INSTALLER" --update
  rm -f "$TMP_INSTALLER"
else
  echo "SAGE: install.sh のダウンロードに失敗しました。次回再試行します。"
  rm -f "$TMP_INSTALLER"
fi

__EOF_TMPL_UPDATE_CHECK__

read -r -d '' TMPL_HOOK_BLOCK_DANGEROUS <<'__EOF_TMPL_HOOK_BLOCK_DANGEROUS__' || true
#!/usr/bin/env bash
# =============================================================================
# TASK-0036: block-dangerous-commands.sh
# Purpose:  PreToolUse hook (Bash matcher) — block dangerous shell commands
# Profile:  standard+ (skipped if profile is "minimal")
# Behavior: Reads JSON from stdin with tool_name and tool_input.command.
#           Blocks patterns: --no-verify, git push --force/-f, rm -rf /|~|.
#           Exit 0 = allow/warn, Exit 2 = block
# =============================================================================
set -euo pipefail

# --- Profile gating ---
PROFILE="standard"
if [ -f ".sage/config.yaml" ]; then
  PROFILE=$(grep -A1 'hooks:' .sage/config.yaml 2>/dev/null | grep 'profile:' | awk '{print $2}' | tr -d '"' || echo "standard")
  [ -z "$PROFILE" ] && PROFILE="standard"
fi

if [ "$PROFILE" = "minimal" ]; then
  exit 0
fi

# --- Read stdin (JSON) ---
INPUT=""
if ! read -r -t 1 INPUT; then
  # Empty stdin or read timeout — never block
  exit 0
fi

if [ -z "$INPUT" ]; then
  exit 0
fi

# --- Parse command from JSON ---
COMMAND=""
if command -v jq &>/dev/null; then
  COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null || true)
else
  # grep fallback: extract command value from JSON
  COMMAND=$(echo "$INPUT" | grep -o '"command"[[:space:]]*:[[:space:]]*"[^"]*"' 2>/dev/null | head -1 | sed 's/.*"command"[[:space:]]*:[[:space:]]*"//;s/"$//' || true)
fi

if [ -z "$COMMAND" ]; then
  # Could not parse command — never block
  exit 0
fi

# --- Check for dangerous patterns ---

# Pattern: --no-verify (bypasses git hooks)
if echo "$COMMAND" | grep -qE '\-\-no-verify'; then
  echo "BLOCKED: Command contains --no-verify which bypasses git hooks." >&2
  echo "Suggestion: Remove --no-verify to ensure quality gates are enforced." >&2
  exit 2
fi

# Pattern: git push --force or git push -f (destructive force push)
if echo "$COMMAND" | grep -qE 'git\s+push\s+.*(\-\-force|\-f)'; then
  echo "BLOCKED: Force push detected (git push --force/-f)." >&2
  echo "Suggestion: Use 'git push --force-with-lease' for safer force pushing." >&2
  exit 2
fi

# Pattern: rm -rf / (wipe root)
if echo "$COMMAND" | grep -qE 'rm\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|(-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*))\s+/\s*$'; then
  echo "BLOCKED: 'rm -rf /' would destroy the entire filesystem." >&2
  echo "Suggestion: Specify a safe, scoped path instead." >&2
  exit 2
fi

# Pattern: rm -rf ~ (wipe home directory)
if echo "$COMMAND" | grep -qE 'rm\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|(-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*))\s+~'; then
  echo "BLOCKED: 'rm -rf ~' would destroy your home directory." >&2
  echo "Suggestion: Specify a safe, scoped path instead." >&2
  exit 2
fi

# Pattern: rm -rf . (wipe current directory)
if echo "$COMMAND" | grep -qE 'rm\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|(-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*))\s+\.\s*$'; then
  echo "BLOCKED: 'rm -rf .' would destroy the current directory." >&2
  echo "Suggestion: Specify a safe, scoped path instead." >&2
  exit 2
fi

# All checks passed
exit 0

__EOF_TMPL_HOOK_BLOCK_DANGEROUS__

read -r -d '' TMPL_HOOK_PROTECT_SAGE <<'__EOF_TMPL_HOOK_PROTECT_SAGE__' || true
#!/usr/bin/env bash
# =============================================================================
# TASK-0037: protect-sage-files.sh
# Purpose:  PreToolUse hook (Edit|Write matcher) — protect SAGE-managed files
# Profile:  standard+ (skipped if profile is "minimal")
# Behavior: Reads JSON from stdin with tool_name and tool_input.file_path.
#           Protected: CLAUDE.md, sage/*, .sage/config.yaml, .claude/settings.json
#           If a TASK with sage-managed: true AND status 実行中 exists, allow.
#           Otherwise block (exit 2).
#           On empty stdin or parse error: exit 0
# =============================================================================
set -euo pipefail

# --- Profile gating ---
PROFILE="standard"
if [ -f ".sage/config.yaml" ]; then
  PROFILE=$(grep -A1 'hooks:' .sage/config.yaml 2>/dev/null | grep 'profile:' | awk '{print $2}' | tr -d '"' || echo "standard")
  [ -z "$PROFILE" ] && PROFILE="standard"
fi

if [ "$PROFILE" = "minimal" ]; then
  exit 0
fi

# --- Read stdin (JSON) ---
INPUT=""
if ! read -r -t 1 INPUT; then
  exit 0
fi

if [ -z "$INPUT" ]; then
  exit 0
fi

# --- Parse file_path from JSON ---
FILE_PATH=""
if command -v jq &>/dev/null; then
  FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
else
  FILE_PATH=$(echo "$INPUT" | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' 2>/dev/null | head -1 | sed 's/.*"file_path"[[:space:]]*:[[:space:]]*"//;s/"$//' || true)
fi

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# --- Check if file is protected ---
IS_PROTECTED=false

# Normalize: strip leading ./ if present
NORM_PATH="${FILE_PATH#./}"

case "$NORM_PATH" in
  CLAUDE.md)
    IS_PROTECTED=true
    ;;
  sage/*)
    IS_PROTECTED=true
    ;;
  .sage/config.yaml)
    IS_PROTECTED=true
    ;;
  .claude/settings.json)
    IS_PROTECTED=true
    ;;
esac

# Also check if the path ends with these (for absolute paths)
if [ "$IS_PROTECTED" = false ]; then
  case "$FILE_PATH" in
    */CLAUDE.md)
      IS_PROTECTED=true
      ;;
    */sage/*)
      IS_PROTECTED=true
      ;;
    */.sage/config.yaml)
      IS_PROTECTED=true
      ;;
    */.claude/settings.json)
      IS_PROTECTED=true
      ;;
  esac
fi

if [ "$IS_PROTECTED" = false ]; then
  # Not a protected file — allow
  exit 0
fi

# --- Check for active sage-managed TASK ---
if [ -d "tasks" ]; then
  for task_file in tasks/*.md; do
    [ -f "$task_file" ] || continue

    # Check if task has sage-managed: true AND status: 実行中
    HAS_SAGE_MANAGED=false
    HAS_ACTIVE_STATUS=false

    if grep -q 'sage-managed:[[:space:]]*true' "$task_file" 2>/dev/null; then
      HAS_SAGE_MANAGED=true
    fi

    if grep -q '実行中' "$task_file" 2>/dev/null; then
      HAS_ACTIVE_STATUS=true
    fi

    if [ "$HAS_SAGE_MANAGED" = true ] && [ "$HAS_ACTIVE_STATUS" = true ]; then
      # Active sage-managed task found — allow edit
      exit 0
    fi
  done
fi

# --- Block: no active sage-managed task ---
echo "BLOCKED: '$NORM_PATH' is a SAGE-protected file." >&2
echo "Protected files: CLAUDE.md, sage/*, .sage/config.yaml, .claude/settings.json" >&2
echo "To modify, ensure a TASK in tasks/ has 'sage-managed: true' and status '実行中'." >&2
exit 2

__EOF_TMPL_HOOK_PROTECT_SAGE__

read -r -d '' TMPL_HOOK_CHECK_SCOPE <<'__EOF_TMPL_HOOK_CHECK_SCOPE__' || true
#!/usr/bin/env bash
# =============================================================================
# TASK-0038: check-file-scope.sh
# Purpose:  PreToolUse hook (Edit|Write matcher) — enforce TASK File Scope
# Profile:  standard+ (warn on stderr, exit 0), strict (block with exit 2)
# Behavior: Reads JSON from stdin with tool_input.file_path.
#           Finds active TASK (status 実行中 in tasks/*.md), extracts File Scope.
#           If file_path is outside scope: warn (standard) or block (strict).
#           If no active TASK found: skip check, exit 0.
#           On empty stdin or parse error: exit 0
# =============================================================================
set -euo pipefail

# --- Profile gating ---
PROFILE="standard"
if [ -f ".sage/config.yaml" ]; then
  PROFILE=$(grep -A1 'hooks:' .sage/config.yaml 2>/dev/null | grep 'profile:' | awk '{print $2}' | tr -d '"' || echo "standard")
  [ -z "$PROFILE" ] && PROFILE="standard"
fi

if [ "$PROFILE" = "minimal" ]; then
  exit 0
fi

# --- Read stdin (JSON) ---
INPUT=""
if ! read -r -t 1 INPUT; then
  exit 0
fi

if [ -z "$INPUT" ]; then
  exit 0
fi

# --- Parse file_path from JSON ---
FILE_PATH=""
if command -v jq &>/dev/null; then
  FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
else
  FILE_PATH=$(echo "$INPUT" | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' 2>/dev/null | head -1 | sed 's/.*"file_path"[[:space:]]*:[[:space:]]*"//;s/"$//' || true)
fi

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# --- Find active TASK (status 実行中) ---
ACTIVE_TASK=""
SCOPE_PATHS=""

if [ ! -d "tasks" ]; then
  echo "No active TASKs found, skipping scope check." >&2
  exit 0
fi

for task_file in tasks/*.md; do
  [ -f "$task_file" ] || continue

  if grep -q '実行中' "$task_file" 2>/dev/null; then
    ACTIVE_TASK="$task_file"
    break
  fi
done

if [ -z "$ACTIVE_TASK" ]; then
  echo "No active TASK found, skipping scope check." >&2
  exit 0
fi

# --- Extract File Scope from active TASK ---
# Look for "File Scope" or "file_scope" section and collect paths
# Typical format:
#   ## File Scope
#   - src/foo/bar.ts
#   - tests/foo/
IN_SCOPE=false
while IFS= read -r line; do
  # Detect File Scope header (various formats)
  if echo "$line" | grep -qiE '^#{1,3}\s+file.?scope'; then
    IN_SCOPE=true
    continue
  fi

  # Stop at next header
  if [ "$IN_SCOPE" = true ] && echo "$line" | grep -qE '^#{1,3}\s+'; then
    break
  fi

  if [ "$IN_SCOPE" = true ]; then
    # Extract path from list items: "- path" or "* path" or "  - path"
    EXTRACTED=$(echo "$line" | sed -n 's/^[[:space:]]*[-*][[:space:]]*\(`\?\)\([^`]*\)\(`\?\)$/\2/p' 2>/dev/null || true)
    if [ -n "$EXTRACTED" ]; then
      SCOPE_PATHS="$SCOPE_PATHS|$EXTRACTED"
    fi
  fi
done < "$ACTIVE_TASK"

if [ -z "$SCOPE_PATHS" ]; then
  # No File Scope defined in TASK — skip check
  exit 0
fi

# --- Check if file_path falls within any scope path ---
# Normalize file_path: strip leading ./
NORM_PATH="${FILE_PATH#./}"

# Also handle absolute paths by extracting relative portion
if [[ "$NORM_PATH" == /* ]]; then
  # Try to make it relative to PWD
  PWD_PREFIX="$(pwd)/"
  NORM_PATH="${NORM_PATH#$PWD_PREFIX}"
fi

IFS='|' read -ra PATHS <<< "$SCOPE_PATHS"
for scope_path in "${PATHS[@]}"; do
  [ -z "$scope_path" ] && continue
  # Strip backticks, leading/trailing whitespace
  scope_path=$(echo "$scope_path" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  [ -z "$scope_path" ] && continue

  # Check if file_path starts with or matches the scope path
  if [[ "$NORM_PATH" == "$scope_path"* ]] || [[ "$NORM_PATH" == "$scope_path" ]]; then
    # Within scope
    exit 0
  fi
done

# --- Out of scope ---
TASK_ID=$(basename "$ACTIVE_TASK" .md)

if [ "$PROFILE" = "strict" ]; then
  echo "BLOCKED: '$NORM_PATH' is outside File Scope for $TASK_ID." >&2
  echo "Allowed paths: ${SCOPE_PATHS//|/, }" >&2
  exit 2
else
  echo "WARNING: '$NORM_PATH' is outside File Scope for $TASK_ID." >&2
  echo "Allowed paths: ${SCOPE_PATHS//|/, }" >&2
  exit 0
fi

__EOF_TMPL_HOOK_CHECK_SCOPE__

read -r -d '' TMPL_HOOK_SESSION_START <<'__EOF_TMPL_HOOK_SESSION_START__' || true
#!/usr/bin/env bash
# =============================================================================
# TASK-0039: session-start.sh
# Purpose:  SessionStart hook (no stdin) — display project context summary
# Profile:  minimal+ (runs for all profiles)
# Behavior: Prints to stdout:
#           1. Latest 3 RUN logs from .sage/runs/ (status, task_id, error_log)
#           2. In-progress/blocked TASKs from tasks/*.md
#           3. Latest 5 entries from sage/failures.md
#           Always exit 0
# =============================================================================
set -euo pipefail

# --- Profile gating ---
PROFILE="minimal"
if [ -f ".sage/config.yaml" ]; then
  PROFILE=$(grep -A1 'hooks:' .sage/config.yaml 2>/dev/null | grep 'profile:' | awk '{print $2}' | tr -d '"' || echo "minimal")
  [ -z "$PROFILE" ] && PROFILE="minimal"
fi

# minimal+ means all profiles run this hook (minimal, standard, strict)
# No profile skip needed.

echo "=== SAGE Session Context ==="
echo ""

# --- 1. Latest 3 RUN logs ---
echo "--- Recent RUN Logs ---"
if [ -d ".sage/runs" ] && ls .sage/runs/*.json &>/dev/null 2>&1; then
  # Get latest 3 files by modification time
  LATEST_RUNS=$(ls -t .sage/runs/*.json 2>/dev/null | head -3)

  for run_file in $LATEST_RUNS; do
    [ -f "$run_file" ] || continue
    RUN_NAME=$(basename "$run_file")

    if command -v jq &>/dev/null; then
      STATUS=$(jq -r '.status // "unknown"' "$run_file" 2>/dev/null || echo "unknown")
      TASK_ID=$(jq -r '.task_id // "N/A"' "$run_file" 2>/dev/null || echo "N/A")
      ERROR_LOG=$(jq -r '.error_log // empty' "$run_file" 2>/dev/null | head -1 || true)
    else
      STATUS=$(grep -o '"status"[[:space:]]*:[[:space:]]*"[^"]*"' "$run_file" 2>/dev/null | head -1 | sed 's/.*"status"[[:space:]]*:[[:space:]]*"//;s/"$//' || echo "unknown")
      TASK_ID=$(grep -o '"task_id"[[:space:]]*:[[:space:]]*"[^"]*"' "$run_file" 2>/dev/null | head -1 | sed 's/.*"task_id"[[:space:]]*:[[:space:]]*"//;s/"$//' || echo "N/A")
      ERROR_LOG=$(grep -o '"error_log"[[:space:]]*:[[:space:]]*"[^"]*"' "$run_file" 2>/dev/null | head -1 | sed 's/.*"error_log"[[:space:]]*:[[:space:]]*"//;s/"$//' | head -1 || true)
    fi

    echo "  $RUN_NAME: status=$STATUS task=$TASK_ID${ERROR_LOG:+ error=$ERROR_LOG}"
  done
elif [ -d ".sage/runs" ] && ls .sage/runs/*.yaml &>/dev/null 2>&1; then
  LATEST_RUNS=$(ls -t .sage/runs/*.yaml 2>/dev/null | head -3)
  for run_file in $LATEST_RUNS; do
    [ -f "$run_file" ] || continue
    RUN_NAME=$(basename "$run_file")
    STATUS=$(grep 'status:' "$run_file" 2>/dev/null | head -1 | awk '{print $2}' || echo "unknown")
    TASK_ID=$(grep 'task_id:' "$run_file" 2>/dev/null | head -1 | awk '{print $2}' || echo "N/A")
    echo "  $RUN_NAME: status=$STATUS task=$TASK_ID"
  done
else
  echo "  No RUN logs found."
fi
echo ""

# --- 2. In-progress / Blocked TASKs ---
echo "--- Active TASKs ---"
FOUND_TASKS=false
if [ -d "tasks" ]; then
  for task_file in tasks/*.md; do
    [ -f "$task_file" ] || continue

    TASK_NAME=$(basename "$task_file" .md)

    # Check for in-progress (実行中) or blocked (ブロック中)
    if grep -q '実行中' "$task_file" 2>/dev/null; then
      echo "  [$TASK_NAME] Status: 実行中 (In Progress)"
      FOUND_TASKS=true
    elif grep -q 'ブロック中' "$task_file" 2>/dev/null; then
      echo "  [$TASK_NAME] Status: ブロック中 (Blocked)"
      FOUND_TASKS=true
    fi
  done
fi

if [ "$FOUND_TASKS" = false ]; then
  echo "  No active TASKs."
fi
echo ""

# --- 3. Latest 5 entries from sage/failures.md ---
echo "--- Recent Failures ---"
if [ -f "sage/failures.md" ]; then
  # Extract failure entries (lines starting with ## or ### as entry headers)
  # Show last 5 entry headers with their first detail line
  ENTRIES=$(grep -n '^##' "sage/failures.md" 2>/dev/null | tail -5)

  if [ -n "$ENTRIES" ]; then
    while IFS= read -r entry; do
      LINE_NUM=$(echo "$entry" | cut -d: -f1)
      HEADER=$(echo "$entry" | cut -d: -f2-)
      # Get next non-empty line as detail
      DETAIL=$(sed -n "$((LINE_NUM + 1)),$((LINE_NUM + 3))p" "sage/failures.md" 2>/dev/null | grep -v '^$' | head -1 || true)
      echo "  $HEADER"
      [ -n "$DETAIL" ] && echo "    $DETAIL"
    done <<< "$ENTRIES"
  else
    echo "  No failure entries found."
  fi
else
  echo "  sage/failures.md not found."
fi

echo ""
echo "=== End Session Context ==="

exit 0

__EOF_TMPL_HOOK_SESSION_START__

read -r -d '' TMPL_HOOK_SESSION_STOP <<'__EOF_TMPL_HOOK_SESSION_STOP__' || true
#!/usr/bin/env bash
# =============================================================================
# TASK-0040: session-stop.sh
# Purpose:  Stop hook (no stdin) — record session metrics
# Profile:  minimal+ (runs for all profiles)
# Behavior: Appends 1 JSON line to .sage/metrics/sessions.jsonl
#           Schema: {"timestamp":"ISO8601","files_changed":N,"files":["path1",...]}
#           Gets changed files from: git diff --name-only HEAD
#           Creates .sage/metrics/ if not exists.
#           Always exit 0
# =============================================================================
set -euo pipefail

# --- Profile gating ---
PROFILE="minimal"
if [ -f ".sage/config.yaml" ]; then
  PROFILE=$(grep -A1 'hooks:' .sage/config.yaml 2>/dev/null | grep 'profile:' | awk '{print $2}' | tr -d '"' || echo "minimal")
  [ -z "$PROFILE" ] && PROFILE="minimal"
fi

# minimal+ means all profiles run this hook
# No profile skip needed.

# --- Ensure metrics directory exists ---
mkdir -p .sage/metrics 2>/dev/null || true

# --- Get changed files from git ---
CHANGED_FILES=""
CHANGED_FILES=$(git diff --name-only HEAD 2>/dev/null || true)

# --- Build JSON line ---
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date +"%Y-%m-%dT%H:%M:%SZ")

if command -v jq &>/dev/null; then
  # Use jq for proper JSON construction
  if [ -n "$CHANGED_FILES" ]; then
    FILES_JSON=$(echo "$CHANGED_FILES" | jq -R -s 'split("\n") | map(select(length > 0))' 2>/dev/null || echo "[]")
    FILES_COUNT=$(echo "$CHANGED_FILES" | grep -c '.' 2>/dev/null || echo "0")
  else
    FILES_JSON="[]"
    FILES_COUNT=0
  fi

  ENTRY=$(jq -n \
    --arg ts "$TIMESTAMP" \
    --argjson count "$FILES_COUNT" \
    --argjson files "$FILES_JSON" \
    '{"timestamp":$ts,"files_changed":$count,"files":$files}' 2>/dev/null || true)

  if [ -n "$ENTRY" ]; then
    echo "$ENTRY" >> .sage/metrics/sessions.jsonl
    exit 0
  fi
fi

# --- Fallback: manual JSON construction ---
FILES_COUNT=0
FILES_ARRAY=""

if [ -n "$CHANGED_FILES" ]; then
  while IFS= read -r file; do
    [ -z "$file" ] && continue
    FILES_COUNT=$((FILES_COUNT + 1))
    if [ -n "$FILES_ARRAY" ]; then
      FILES_ARRAY="$FILES_ARRAY,\"$file\""
    else
      FILES_ARRAY="\"$file\""
    fi
  done <<< "$CHANGED_FILES"
fi

echo "{\"timestamp\":\"$TIMESTAMP\",\"files_changed\":$FILES_COUNT,\"files\":[$FILES_ARRAY]}" >> .sage/metrics/sessions.jsonl

exit 0

__EOF_TMPL_HOOK_SESSION_STOP__

read -r -d '' TMPL_SETTINGS_JSON <<'__EOF_TMPL_SETTINGS_JSON__' || true
{
  "permissions": {
    "allow": [],
    "deny": []
  },
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": "bash templates/hooks/block-dangerous-commands.sh"
          }
        ]
      },
      {
        "matcher": "Edit|Write",
        "hooks": [
          {
            "type": "command",
            "command": "bash templates/hooks/protect-sage-files.sh"
          },
          {
            "type": "command",
            "command": "bash templates/hooks/check-file-scope.sh"
          }
        ]
      }
    ],
    "SessionStart": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "bash templates/hooks/session-start.sh"
          }
        ]
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "bash templates/hooks/session-stop.sh"
          }
        ]
      }
    ]
  }
}

__EOF_TMPL_SETTINGS_JSON__

# === Main Logic ===

SAGE_START_MARKER="<!-- === SAGE Development System (auto-injected) === -->"
SAGE_END_MARKER="<!-- === End SAGE === -->"

show_version() {
  echo "SAGE Development System v${SAGE_VERSION}"
}

check_installed_version() {
  if [ -f ".sage/version" ]; then
    cat ".sage/version"
  else
    echo ""
  fi
}

write_file_if_new() {
  local path="$1"
  local content="$2"
  local dir=$(dirname "$path")
  mkdir -p "$dir"

  if [ -f "$path" ]; then
    echo "  SKIP: $path (already exists)"
    return 0
  else
    echo "$content" > "$path"
    echo "  CREATE: $path"
    return 0
  fi
}

update_file() {
  local path="$1"
  local content="$2"
  local dir=$(dirname "$path")
  mkdir -p "$dir"
  echo "$content" > "$path"
  echo "  UPDATE: $path"
}

upsert_sage_section() {
  local file="$1"
  local snippet="$2"

  if [ ! -f "$file" ]; then
    echo "$snippet" > "$file"
    echo "  CREATE: $file"
    return
  fi

  if grep -qF "$SAGE_START_MARKER" "$file"; then
    # SAGEセクションが既にある → マーカー間を置換
    local tmp_before=$(mktemp)
    local tmp_after=$(mktemp)
    local tmp_result=$(mktemp)

    # マーカーの行番号を取得
    local start_line=$(grep -nF "$SAGE_START_MARKER" "$file" | head -1 | cut -d: -f1)
    local end_line=$(grep -nF "$SAGE_END_MARKER" "$file" | tail -1 | cut -d: -f1)

    # マーカー前の部分
    if [ "$start_line" -gt 1 ]; then
      sed -n "1,$((start_line - 1))p" "$file" > "$tmp_before"
    else
      : > "$tmp_before"
    fi

    # マーカー後の部分
    local total_lines=$(wc -l < "$file" | tr -d ' ')
    if [ "$end_line" -lt "$total_lines" ]; then
      sed -n "$((end_line + 1)),\$p" "$file" > "$tmp_after"
    else
      : > "$tmp_after"
    fi

    # 結合: before + new snippet + after
    cat "$tmp_before" > "$tmp_result"
    echo "$snippet" >> "$tmp_result"
    cat "$tmp_after" >> "$tmp_result"

    mv "$tmp_result" "$file"
    rm -f "$tmp_before" "$tmp_after"
    echo "  UPDATE: $file (SAGE section replaced)"
  else
    echo "" >> "$file"
    echo "$snippet" >> "$file"
    echo "  APPEND: $file (SAGE section added)"
  fi
}

setup_commit_hook() {
  if [ ! -d .git ]; then
    echo "  SKIP: not a git repository"
    return
  fi

  local hook_dir=".git/hooks"
  if [ -d .husky ]; then
    hook_dir=".husky"
  fi

  local hook_file="$hook_dir/commit-msg"

  if [ -f "$hook_file" ] && grep -qF "SAGE" "$hook_file"; then
    echo "  SKIP: $hook_file (SAGE hook already present)"
  elif [ -f "$hook_file" ]; then
    echo "" >> "$hook_file"
    echo "# --- SAGE: TASK-ID check ---" >> "$hook_file"
    echo "$TMPL_COMMIT_HOOK" >> "$hook_file"
    echo "  APPEND: $hook_file"
  else
    mkdir -p "$hook_dir"
    echo "$TMPL_COMMIT_HOOK" > "$hook_file"
    chmod +x "$hook_file"
    echo "  CREATE: $hook_file"
  fi
}

audit_existing_claude_md() {
  local file="$1"
  local report=".sage/adoption-audit.md"

  echo "# SAGE Adoption Audit" > "$report"
  echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$report"
  echo "" >> "$report"

  local rules=$(grep -E "^[\t ]*[-*]" "$file" | grep -v "^#" | grep -v '^\s*$')

  echo "## Analysis" >> "$report"
  echo "" >> "$report"

  echo "### SAFE_AUTO_APPLY" >> "$report"
  echo "These rules do not conflict with SAGE. No action needed." >> "$report"
  echo "$rules" | while IFS= read -r line; do
    if [ -n "$line" ] && ! echo "$line" | grep -qiE "commit|task|spec|todo|fixme|test|scope|review"; then
      echo "- $line" >> "$report"
    fi
  done
  echo "" >> "$report"

  echo "### NEEDS_REVIEW" >> "$report"
  echo "These rules may overlap with SAGE. Review recommended." >> "$report"
  echo "$rules" | while IFS= read -r line; do
    if [ -n "$line" ] && echo "$line" | grep -qiE "spec|scope|review|test|coverage"; then
      if ! echo "$line" | grep -qiE "commit.*id|task.*id|no commit|skip test"; then
        echo "- $line" >> "$report"
      fi
    fi
  done
  echo "" >> "$report"

  echo "### CONFLICT" >> "$report"
  echo "These rules may conflict with SAGE. Do NOT auto-merge." >> "$report"
  echo "$rules" | while IFS= read -r line; do
    if [ -n "$line" ] && echo "$line" | grep -qiE "commit.*message|commit.*format|task.*id|ticket.*id|todo.*ok|fixme.*allow|skip.*test"; then
      echo "- $line (conflicts with SAGE commit/test rules)" >> "$report"
    fi
  done
  echo "" >> "$report"

  echo "## Recommendation" >> "$report"
  echo "- SAFE_AUTO_APPLY items: no action needed" >> "$report"
  echo "- NEEDS_REVIEW items: check if your project rules and SAGE rules overlap. Remove duplicates." >> "$report"
  echo "- CONFLICT items: resolve manually before relying on SAGE enforcement." >> "$report"

  echo "  AUDIT: Report written to $report"
}

setup_gitignore() {
  if [ ! -f .gitignore ]; then
    touch .gitignore
  fi
  grep -qxF '.sage/runs/' .gitignore 2>/dev/null || echo '.sage/runs/' >> .gitignore
  grep -qxF '.sage/metrics/' .gitignore 2>/dev/null || echo '.sage/metrics/' >> .gitignore
  echo "  OK"
}

# --- Parse arguments ---
MODE="install"
for arg in "$@"; do
  case "$arg" in
    --update) MODE="update" ;;
    --version) show_version; exit 0 ;;
    --help)
      echo "Usage: bash install.sh [--update] [--version]"
      echo "  (no args)  First-time installation"
      echo "  --update   Update SAGE to v${SAGE_VERSION}"
      echo "  --version  Show version"
      exit 0
      ;;
  esac
done

INSTALLED_VERSION=$(check_installed_version)

# Auto-detect: if already installed, switch to update mode
if [ -n "$INSTALLED_VERSION" ] && [ "$MODE" = "install" ]; then
  echo "SAGE v${INSTALLED_VERSION} is already installed."
  echo "Updating to v${SAGE_VERSION}..."
  echo ""
  MODE="update"
fi

if [ "$MODE" = "update" ] && [ "$INSTALLED_VERSION" = "$SAGE_VERSION" ]; then
  echo "Already at v${SAGE_VERSION}. No update needed."
  exit 0
fi

echo "========================================="
if [ "$MODE" = "install" ]; then
  echo "  SAGE v${SAGE_VERSION} — New Installation"
else
  echo "  SAGE v${INSTALLED_VERSION:-?} → v${SAGE_VERSION} — Update"
fi
echo "========================================="
echo ""

# --- [1/9] Directories ---
echo "[1/9] ディレクトリ..."
mkdir -p specs plans tasks sage .sage/runs .sage/metrics docs scripts .claude/rules .claude/skills/sage-spec .claude/skills/sage-plan .claude/skills/sage-review .claude/skills/sage-evaluate/references
echo "  OK"

# --- [2/9] Templates & governance ---
echo ""
echo "[2/9] テンプレート & ガバナンス文書..."
if [ "$MODE" = "install" ]; then
  write_file_if_new "specs/_template.md" "$TMPL_SPEC"
  write_file_if_new "plans/_template.md" "$TMPL_PLAN"
  write_file_if_new "tasks/_template.md" "$TMPL_TASK"
  write_file_if_new "sage/charter.md" "$TMPL_CHARTER"
  write_file_if_new "sage/governance.md" "$TMPL_GOVERNANCE"
  write_file_if_new "sage/failures.md" "$TMPL_FAILURES"
  write_file_if_new "sage/anti-patterns.md" "$TMPL_ANTIPATTERNS"
  write_file_if_new "sage/quality-gates.md" "$TMPL_QUALITY_GATES"
  write_file_if_new "sage/adoption-phases.md" "$TMPL_ADOPTION"
  write_file_if_new "sage/traceability.md" "$TMPL_TRACEABILITY"
  write_file_if_new ".sage/config.yaml" "$TMPL_CONFIG"
  write_file_if_new "scripts/sage-validate.sh" "$TMPL_VALIDATE" && chmod +x "scripts/sage-validate.sh"
  write_file_if_new "scripts/sage-id-gen.sh" "$TMPL_ID_GEN" && chmod +x "scripts/sage-id-gen.sh"
  write_file_if_new "scripts/sage-trace-check.sh" "$TMPL_TRACE_CHECK" && chmod +x "scripts/sage-trace-check.sh"
  write_file_if_new "scripts/sage-update-check.sh" "$TMPL_UPDATE_CHECK" && chmod +x "scripts/sage-update-check.sh"
else
  # Update mode: テンプレートとガバナンスはSAGE管理なので上書き
  update_file "specs/_template.md" "$TMPL_SPEC"
  update_file "plans/_template.md" "$TMPL_PLAN"
  update_file "tasks/_template.md" "$TMPL_TASK"
  update_file "sage/charter.md" "$TMPL_CHARTER"
  update_file "sage/governance.md" "$TMPL_GOVERNANCE"
  update_file "sage/anti-patterns.md" "$TMPL_ANTIPATTERNS"
  update_file "sage/quality-gates.md" "$TMPL_QUALITY_GATES"
  update_file "sage/adoption-phases.md" "$TMPL_ADOPTION"
  update_file "sage/traceability.md" "$TMPL_TRACEABILITY"
  update_file "scripts/sage-validate.sh" "$TMPL_VALIDATE" && chmod +x "scripts/sage-validate.sh"
  update_file "scripts/sage-id-gen.sh" "$TMPL_ID_GEN" && chmod +x "scripts/sage-id-gen.sh"
  update_file "scripts/sage-trace-check.sh" "$TMPL_TRACE_CHECK" && chmod +x "scripts/sage-trace-check.sh"
  update_file "scripts/sage-update-check.sh" "$TMPL_UPDATE_CHECK" && chmod +x "scripts/sage-update-check.sh"
  # failures.md, config.yaml はプロジェクト固有データが入るので更新しない
  echo "  KEEP: sage/failures.md (project data)"
  echo "  KEEP: .sage/config.yaml (project settings)"
fi

# --- [3/9] .claude/rules/ ---
echo ""
echo "[3/9] .claude/rules/..."
if [ "$MODE" = "install" ]; then
  write_file_if_new ".claude/rules/specs-rules.md" "$TMPL_RULES_SPECS"
  write_file_if_new ".claude/rules/plans-rules.md" "$TMPL_RULES_PLANS"
  write_file_if_new ".claude/rules/tasks-rules.md" "$TMPL_RULES_TASKS"
  write_file_if_new ".claude/rules/src-rules.md" "$TMPL_RULES_SRC"
  write_file_if_new ".claude/rules/sage-governance-rules.md" "$TMPL_RULES_GOVERNANCE"
else
  update_file ".claude/rules/specs-rules.md" "$TMPL_RULES_SPECS"
  update_file ".claude/rules/plans-rules.md" "$TMPL_RULES_PLANS"
  update_file ".claude/rules/tasks-rules.md" "$TMPL_RULES_TASKS"
  update_file ".claude/rules/src-rules.md" "$TMPL_RULES_SRC"
  update_file ".claude/rules/sage-governance-rules.md" "$TMPL_RULES_GOVERNANCE"
fi

# --- [4/9] .claude/skills/ ---
echo ""
echo "[4/9] .claude/skills/..."
if [ "$MODE" = "install" ]; then
  write_file_if_new ".claude/skills/sage-spec/SKILL.md" "$TMPL_SKILL_SPEC"
  write_file_if_new ".claude/skills/sage-plan/SKILL.md" "$TMPL_SKILL_PLAN"
  write_file_if_new ".claude/skills/sage-review/SKILL.md" "$TMPL_SKILL_REVIEW"
  write_file_if_new ".claude/skills/sage-evaluate/SKILL.md" "$TMPL_SKILL_EVALUATE"
  write_file_if_new ".claude/skills/sage-evaluate/references/scoring-rubric.md" "$TMPL_SKILL_EVALUATE_RUBRIC"
  write_file_if_new ".claude/skills/sage-evaluate/references/knowledge-base.md" "$TMPL_SKILL_EVALUATE_KB"
else
  update_file ".claude/skills/sage-spec/SKILL.md" "$TMPL_SKILL_SPEC"
  update_file ".claude/skills/sage-plan/SKILL.md" "$TMPL_SKILL_PLAN"
  update_file ".claude/skills/sage-review/SKILL.md" "$TMPL_SKILL_REVIEW"
  update_file ".claude/skills/sage-evaluate/SKILL.md" "$TMPL_SKILL_EVALUATE"
  update_file ".claude/skills/sage-evaluate/references/scoring-rubric.md" "$TMPL_SKILL_EVALUATE_RUBRIC"
  update_file ".claude/skills/sage-evaluate/references/knowledge-base.md" "$TMPL_SKILL_EVALUATE_KB"
fi

# --- [5/9] CLAUDE.md ---
echo ""
echo "[5/9] CLAUDE.md..."
# Audit existing CLAUDE.md before first SAGE injection
AUDIT_GENERATED=""
if [ -f CLAUDE.md ] && [ -s CLAUDE.md ] && ! grep -qF "$SAGE_START_MARKER" CLAUDE.md; then
  audit_existing_claude_md CLAUDE.md
  AUDIT_GENERATED="true"
fi
upsert_sage_section "CLAUDE.md" "$TMPL_CLAUDE_SNIPPET"

# --- [6/9] AGENTS.md ---
echo ""
echo "[6/9] AGENTS.md (Codex)..."
upsert_sage_section "AGENTS.md" "$TMPL_AGENTS_SNIPPET"

# --- [7/9] Hooks ---
echo ""
echo "[7/9] Claude Code hooks..."
mkdir -p templates/hooks
if [ "$MODE" = "install" ]; then
  write_file_if_new "templates/hooks/block-dangerous-commands.sh" "$TMPL_HOOK_BLOCK_DANGEROUS" && chmod +x "templates/hooks/block-dangerous-commands.sh"
  write_file_if_new "templates/hooks/protect-sage-files.sh" "$TMPL_HOOK_PROTECT_SAGE" && chmod +x "templates/hooks/protect-sage-files.sh"
  write_file_if_new "templates/hooks/check-file-scope.sh" "$TMPL_HOOK_CHECK_SCOPE" && chmod +x "templates/hooks/check-file-scope.sh"
  write_file_if_new "templates/hooks/session-start.sh" "$TMPL_HOOK_SESSION_START" && chmod +x "templates/hooks/session-start.sh"
  write_file_if_new "templates/hooks/session-stop.sh" "$TMPL_HOOK_SESSION_STOP" && chmod +x "templates/hooks/session-stop.sh"
else
  update_file "templates/hooks/block-dangerous-commands.sh" "$TMPL_HOOK_BLOCK_DANGEROUS" && chmod +x "templates/hooks/block-dangerous-commands.sh"
  update_file "templates/hooks/protect-sage-files.sh" "$TMPL_HOOK_PROTECT_SAGE" && chmod +x "templates/hooks/protect-sage-files.sh"
  update_file "templates/hooks/check-file-scope.sh" "$TMPL_HOOK_CHECK_SCOPE" && chmod +x "templates/hooks/check-file-scope.sh"
  update_file "templates/hooks/session-start.sh" "$TMPL_HOOK_SESSION_START" && chmod +x "templates/hooks/session-start.sh"
  update_file "templates/hooks/session-stop.sh" "$TMPL_HOOK_SESSION_STOP" && chmod +x "templates/hooks/session-stop.sh"
fi
# Deploy settings.json with hook definitions
if [ ! -f ".claude/settings.json" ] || ! grep -qF "block-dangerous-commands" ".claude/settings.json" 2>/dev/null; then
  mkdir -p .claude
  echo "$TMPL_SETTINGS_JSON" > ".claude/settings.json"
  echo "  CREATE: .claude/settings.json (with hooks)"
else
  echo "  SKIP: .claude/settings.json (hooks already configured)"
fi

# --- [8/9] Commit hook ---
echo ""
echo "[8/9] Pre-commit hook..."
setup_commit_hook

# --- [9/9] .gitignore ---
echo ""
echo "[9/9] .gitignore..."
setup_gitignore

# --- Save installed version ---
echo "$SAGE_VERSION" > .sage/version

# --- Generate install-state.yaml (SPEC-0004) ---
echo ""
echo "Generating install-state.yaml..."
generate_install_state() {
  local state_file=".sage/install-state.yaml"
  local sha_cmd=""

  # Cross-platform SHA256
  if command -v sha256sum &>/dev/null; then
    sha_cmd="sha256sum"
  elif command -v shasum &>/dev/null; then
    sha_cmd="shasum -a 256"
  else
    echo "  WARN: No sha256 command found. Skipping install-state generation."
    return
  fi

  cat > "$state_file" <<STATEHEADER
version: "${SAGE_VERSION}"
installed_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
files:
STATEHEADER

  # SAGE-managed files (update_file targets — overwritten on update)
  local managed_files=(
    "specs/_template.md"
    "plans/_template.md"
    "tasks/_template.md"
    "sage/charter.md"
    "sage/governance.md"
    "sage/anti-patterns.md"
    "sage/quality-gates.md"
    "sage/adoption-phases.md"
    "sage/traceability.md"
    "scripts/sage-validate.sh"
    "scripts/sage-id-gen.sh"
    "scripts/sage-trace-check.sh"
    "scripts/sage-update-check.sh"
    ".claude/rules/specs-rules.md"
    ".claude/rules/plans-rules.md"
    ".claude/rules/tasks-rules.md"
    ".claude/rules/src-rules.md"
    ".claude/rules/sage-governance-rules.md"
    ".claude/skills/sage-spec/SKILL.md"
    ".claude/skills/sage-plan/SKILL.md"
    ".claude/skills/sage-review/SKILL.md"
    ".claude/skills/sage-evaluate/SKILL.md"
    ".claude/skills/sage-evaluate/references/scoring-rubric.md"
    ".claude/skills/sage-evaluate/references/knowledge-base.md"
    "templates/hooks/block-dangerous-commands.sh"
    "templates/hooks/protect-sage-files.sh"
    "templates/hooks/check-file-scope.sh"
    "templates/hooks/session-start.sh"
    "templates/hooks/session-stop.sh"
  )

  # User-customizable files (write_file_if_new targets — NOT overwritten)
  local user_files=(
    "CLAUDE.md"
    "AGENTS.md"
    ".sage/config.yaml"
    "sage/failures.md"
    ".claude/settings.json"
  )

  for f in "${managed_files[@]}"; do
    if [ -f "$f" ]; then
      local hash=$($sha_cmd "$f" | awk '{print $1}')
      echo "  - path: \"$f\"" >> "$state_file"
      echo "    sha256: \"$hash\"" >> "$state_file"
      echo "    source: \"embedded\"" >> "$state_file"
      echo "    managed: true" >> "$state_file"
    fi
  done

  for f in "${user_files[@]}"; do
    if [ -f "$f" ]; then
      local hash=$($sha_cmd "$f" | awk '{print $1}')
      echo "  - path: \"$f\"" >> "$state_file"
      echo "    sha256: \"$hash\"" >> "$state_file"
      echo "    source: \"embedded\"" >> "$state_file"
      echo "    managed: false" >> "$state_file"
    fi
  done

  echo "  OK: .sage/install-state.yaml"
}
generate_install_state

echo ""
echo "========================================="
echo "  SAGE v${SAGE_VERSION} — Complete"
echo "========================================="
echo ""
if [ "$MODE" = "install" ]; then
  echo "AI エージェントは次のセッションから自動的にSAGEに従います。"
  echo ""
  echo "次のステップ:"
  if [ "$AUDIT_GENERATED" = "true" ]; then
    echo "  ⚠ 既存の CLAUDE.md にルールが検出されました。"
    echo "    まず監査レポートを確認してください："
    echo "      cat .sage/adoption-audit.md"
    echo ""
    echo "    - SAFE_AUTO_APPLY → 対応不要"
    echo "    - NEEDS_REVIEW    → SAGEと重複していないか確認、重複は削除"
    echo "    - CONFLICT        → 手動で解決してからSAGEを利用"
    echo ""
  fi
  echo "  1. 次の機能開発で SPEC を書いてみる"
  echo "     bash scripts/sage-id-gen.sh spec"
  echo ""
  echo "カスタマイズ:"
  echo "  CLAUDE.md     → SAGEマーカーの上に自由に追記OK"
  echo "  .claude/rules/ → 自分用ルールは別名で追加（例: my-api-rules.md）"
  echo "                   ※ SAGE管理ファイル（specs-rules.md 等）は更新時に上書きされます"
else
  echo "更新内容:"
  echo "  - テンプレート・ガバナンス文書を v${SAGE_VERSION} に更新"
  echo "  - CLAUDE.md / AGENTS.md の SAGE セクションを更新"
  echo "  - プロジェクト固有の設定 (config.yaml, failures.md) はそのまま"
fi
echo ""
