#!/bin/bash
# generate-installer.sh — テンプレートファイルを埋め込んだ自己完結型 install.sh を生成する
# Usage: bash scripts/generate-installer.sh > install.sh
#
# SPEC-0014: modular structure — embed_file calls live in scripts/generator/*.sh,
# this orchestrator only defines helpers + sources modules in numeric order.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
GENERATOR_DIR="${SCRIPT_DIR}/generator"

# バージョン（sage-ai-template 更新時にインクリメント）
VERSION_FILE="$ROOT/.sage-version"
if [ -f "$VERSION_FILE" ]; then
  VERSION=$(cat "$VERSION_FILE")
else
  VERSION="0.1.0"
fi

# ファイルを heredoc として埋め込む関数
embed_file() {
  local var_name="$1"
  local file_path="$2"
  local delimiter="__EOF_${var_name}__"

  if [ ! -f "$file_path" ]; then
    echo "WARN: $file_path not found, skipping" >&2
    echo "${var_name}=''"
    return
  fi

  echo "read -r -d '' ${var_name} <<'${delimiter}' || true"
  cat "$file_path"
  echo ""
  echo "${delimiter}"
}

# --- 生成開始 ---
cat <<'HEADER'
#!/bin/bash
# ============================================
# SAGE Development System — Installer
# ============================================
# 自己完結型。このスクリプトだけで SAGE を導入・更新できます。
#
# 新規導入: bash install.sh
# 更新:     bash install.sh --update
# バージョン確認: bash install.sh --version
#
# Generated by: scripts/generate-installer.sh
# ============================================
set -euo pipefail

HEADER

echo "SAGE_VERSION=\"${VERSION}\""
echo ""

# テンプレートファイルを埋め込む
echo "# === Embedded templates ==="
echo ""

# Source generator modules in numeric order (01-templates.sh ... 07-installer-main.sh).
# Each module is a fragment that calls embed_file (or emits the heredoc for module 07).
# See scripts/generator/README.md for module structure + new SPEC addition workflow.
if [ ! -d "$GENERATOR_DIR" ]; then
  echo "ERROR: generator modules not found at $GENERATOR_DIR" >&2
  exit 1
fi

shopt -s nullglob
modules=( "${GENERATOR_DIR}"/[0-9][0-9]-*.sh )
shopt -u nullglob

if [ "${#modules[@]}" -eq 0 ]; then
  echo "ERROR: no generator modules in $GENERATOR_DIR" >&2
  exit 1
fi

for module in "${modules[@]}"; do
  # shellcheck source=/dev/null
  source "$module"
done
